/** The api in detail: signing in, then one policy saved end to end (nginx, the token,
 * the body check, the commit, the task, the answer, the page noticing the worker), then
 * the other changes and what happens when Redis is down. */
import { geometry, node } from "./player.js";

const nodes = {
  page: node(139, 122, 206, 72, "start", "console page", "Sign in"),
  storage: node(139, 280, 206, 62, "data", "localStorage", "empty", { mono: true }),
  poll: node(139, 432, 206, 62, "svc", "page timer", "off", { idle: "off" }),
  nginx: node(367, 282, 130, 72, "svc", "nginx :8080", "/api/* → api", { mono: true }),
  app: node(604, 122, 208, 62, "svc", "FastAPI app", "match the route"),
  auth: node(852, 122, 208, 62, "ask", "CurrentUser", "JWT · HS256 · 12 h"),
  valid: node(604, 282, 208, 62, "ask", "body check", "Pydantic · 422 if wrong"),
  handler: node(852, 282, 208, 62, "svc", "route handler", "routes/*.py", { mono: true }),
  resp: node(604, 452, 208, 62, "ok", "the answer", "JSON + status code"),
  save: node(852, 420, 208, 62, "svc", "save()", "commit · 409 if taken", { mono: true }),
  enq: node(852, 546, 208, 62, "queue", "enqueue()", "after the commit", { mono: true }),
  pg: node(1112, 152, 196, 92, "data", "Postgres", "users · policies · gaps"),
  lane: node(1112, 356, 196, 92, "queue", "main lane", "rci:tasks", { slots: 2, mono: true }),
  worker: node(1112, 522, 196, 62, "svc", "worker", "waiting", { idle: "waiting", link: "worker" }),
};

const { at, line, curve } = geometry(nodes);

const edges = {
  "page>nginx": curve(at("page", "r"), [276, 122], [306, 184], at("nginx", "t", -20)),
  "storage>page": line(at("storage", "t"), at("page", "b")),
  "poll>nginx": curve(at("poll", "r"), [276, 432], [306, 372], at("nginx", "b", -20)),
  "nginx>app": curve(at("nginx", "r", -16), [466, 266], [466, 122], at("app", "l")),
  "app>auth": line(at("app", "r"), at("auth", "l")),
  "auth>pg": curve(at("auth", "r"), [992, 122], [992, 140], at("pg", "l", -12)),
  "auth>handler": line(at("auth", "b"), at("handler", "t")),
  "app>valid": line(at("app", "b"), at("valid", "t")),
  "app>handler": line(at("app", "b", 66), at("handler", "t", -66)),
  "valid>handler": line(at("valid", "r"), at("handler", "l")),
  "valid>resp": line(at("valid", "b"), at("resp", "t")),
  "handler>pg": curve(at("handler", "r", -10), [992, 272], [992, 170], at("pg", "l", 18)),
  "handler>save": line(at("handler", "b"), at("save", "t")),
  "handler>resp": curve(at("handler", "b", -66), [786, 372], [640, 372], at("resp", "t", 36)),
  "save>pg": curve(at("save", "r", -10), [998, 410], [998, 184], at("pg", "l", 32)),
  "save>enq": line(at("save", "b"), at("enq", "t")),
  "enq>lane": curve(at("enq", "r"), [992, 546], [992, 366], at("lane", "l", 10)),
  "enq>resp": curve(at("enq", "l"), [690, 546], [604, 506], at("resp", "b")),
  "resp>nginx": curve(at("resp", "l"), [462, 452], [462, 298], at("nginx", "r", 16)),
  "lane>worker": line(at("lane", "b"), at("worker", "t")),
  "worker>pg": curve(at("worker", "r"), [1232, 522], [1232, 152], at("pg", "r")),
};

const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9…";

const steps = [
  // ── Story 1: signing in ──
  {
    story: 0, dur: 5600, focus: ["page", "nginx", "app"],
    title: "Sign in",
    text: "The login form posts your email and password to /api/auth/login. nginx strips /api and passes the request on to the api container.",
    code: "loginPage() · frontend/js/views/auth.js · location /api/ · frontend/nginx.conf",
    moves: [["POST /auth/login", "page>nginx", 0.05, 0.42, "start"], ["POST", "nginx>app", 0.52, 0.88, "start"]],
    marks: [[0.42, { log: ["http", "POST /api/auth/login  {\"email\": \"you@company.com\", \"password\": \"…\"}  → nginx → api:8000 /auth/login", "The login form sends your email and password. nginx passes the request to the api, taking /api off the address."] }]],
  },
  {
    story: 0, dur: 6200, focus: ["valid", "handler", "pg"],
    title: "Check the password",
    text: "The body is checked first, then log_in() finds the user by email and compares the password with its salted scrypt hash. Wrong email or password: 401.",
    code: "log_in() · api/routes/auth.py · password_ok() · api/auth.py",
    moves: [["JSON", "app>valid", 0.03, 0.2, "start"], ["Login ✓", "valid>handler", 0.23, 0.4, "ask"],
            ["SELECT user", "handler>pg", 0.45, 0.62, "data"], ["scrypt hash", "pg>handler", 0.66, 0.84, "data"]],
    marks: [
      [0.4, { sub: { handler: "log_in()" } }],
      [0.62, { log: ["sql", "SELECT * FROM users WHERE email = 'you@company.com'", "The api looks you up by your email."] }],
      [0.9, { log: ["app", "scrypt(password, salt, n=2^14, r=8, p=1) matches the stored hash", "Your password is scrambled the same slow way as when you signed up, and the results are compared. The password itself is never stored."] }],
    ],
  },
  {
    story: 0, dur: 6000, focus: ["handler", "resp", "page"],
    title: "A login token",
    text: "It signs a JWT naming your user id, valid 12 hours (TOKEN_HOURS), with JWT_SECRET, or a key the api made once and keeps in Postgres.",
    code: "issue_token(), signing_key() · api/auth.py",
    moves: [["token", "handler>resp", 0.05, 0.32, "ok"], ["200 + token", "resp>nginx", 0.38, 0.62, "ok"],
            ["200 + token", "nginx>page", 0.66, 0.92, "ok"]],
    marks: [[0.32, { log: ["http", `200 OK  {"user": {…}, "company": {…}, "token": "${TOKEN}"}`, "Login worked. The answer includes a token: a signed pass the page sends with every request from now on."] }]],
  },
  {
    story: 0, dur: 5400, focus: ["page", "storage"],
    title: "Kept in the browser",
    text: "The console keeps the token in localStorage (rci.session), so a reload stays signed in, and sends it with every call: Authorization: Bearer …",
    code: "signIn() · frontend/js/app/session.js · api() · frontend/js/lib/api.js",
    moves: [["token", "page>storage", 0.15, 0.6, "data"]],
    marks: [[0.6, { sub: { storage: "rci.session: token, user", page: "signed in · Overview", handler: "routes/*.py" } }]],
  },

  // ── Story 2: saving a new policy ──
  {
    story: 1, dur: 6000, focus: ["page", "storage", "nginx"],
    title: "Press Save",
    text: "New policy, then Save: POST /api/policies with the code, title, owner, regulators and text as JSON, and your token in the Authorization header.",
    code: "newPolicyPage() · frontend/js/views/policies.js",
    moves: [["token", "storage>page", 0.03, 0.25, "data"], ["POST /policies", "page>nginx", 0.32, 0.62, "start"],
            ["POST", "nginx>app", 0.68, 0.95, "start"]],
    marks: [
      [0.02, { sub: { page: "Policies · New policy" } }],
      [0.62, { log: ["http", `POST /api/policies  Authorization: Bearer ${TOKEN}  {"code": "POL-AML", "title": "Anti-Money Laundering Policy", "regulators": ["RBI"], …}`, "Saving the new policy: its fields as JSON, plus your token so the api knows who you are."] }],
    ],
  },
  {
    story: 1, dur: 6400, focus: ["app", "auth", "pg"],
    title: "Who's calling?",
    text: "CurrentUser checks the token's signature and expiry, then loads your user. No token, an expired or a forged one: 401, and the console shows Sign in.",
    code: "current_user(), CurrentUser · api/auth.py",
    moves: [["Bearer eyJ…", "app>auth", 0.03, 0.26, "ask"], ["user 1?", "auth>pg", 0.32, 0.55, "data"],
            ["user · company 1", "pg>auth", 0.6, 0.86, "data"]],
    marks: [
      [0.3, { log: ["app", "jwt.decode(token, key, HS256) → {sub: '1', exp: in 11 h 58 min}", "The api checks the token's signature with its secret key: genuine, it's user 1's, and valid for almost 12 more hours."] }],
      [0.55, { log: ["sql", "SELECT * FROM users WHERE id = 1", "It loads user 1, and with it your company. Everything after this touches only your company's rows."] }],
      [0.86, { sub: { auth: "user 1 · company 1" } }],
    ],
  },
  {
    story: 1, dur: 5600, focus: ["app", "valid", "handler"],
    title: "Check the body",
    text: "PolicyIn checks the fields before any code of ours runs: a missing title or a wrong type answers 422, naming exactly which field is wrong.",
    code: "PolicyIn · common/models.py",
    moves: [["JSON", "app>valid", 0.05, 0.4, "start"], ["PolicyIn ✓", "valid>handler", 0.5, 0.88, "ask"]],
    marks: [[0.4, { sub: { valid: "✓ code, title, owner, text" } }]],
  },
  {
    story: 1, dur: 5600, focus: ["handler"],
    title: "Only your company",
    text: "create_policy() stamps the policy with your company_id. Every query filters by it: another company's policy is a 404 to you, never a 403.",
    code: "create_policy() · api/routes/policies.py · get_or_404() · api/database.py",
    moves: [],
    marks: [[0.2, { sub: { handler: "create_policy()", auth: "JWT · HS256 · 12 h", valid: "Pydantic · 422 if wrong" } }]],
  },
  {
    story: 1, dur: 6400, focus: ["handler", "save", "pg"],
    title: "Save it",
    text: "save() adds the row and commits: version 1, no embeddings yet. A code your library already has breaks a unique constraint: 409.",
    code: "save() · api/database.py",
    moves: [["Policy", "handler>save", 0.03, 0.25, "svc"], ["INSERT", "save>pg", 0.3, 0.6, "data"],
            ["id 11", "pg>save", 0.66, 0.92, "data"]],
    marks: [[0.6, { sub: { pg: "POL-AML v1 · id 11" },
                    log: [["sql", "INSERT INTO policies (company_id, code, title, owner, regulators, text, version) VALUES (1, 'POL-AML', 'Anti-Money Laundering Policy', …, 1) → id 11", "The policy is saved: id 11, version 1, for company 1."],
                          ["sql", "COMMIT", "Postgres saves everything so far for good, all together. Until this line nothing was saved, so a failure would have undone it all."]] }]],
  },
  {
    story: 1, dur: 6800, focus: ["save", "enq", "lane"],
    title: "Then queue the check",
    text: "Only after the commit: enqueue() sets the task's key (SET … NX) and XADDs policy.check to the main lane, so the worker always finds the row.",
    code: "enqueue_or_undo(), enqueue() · api/database.py · enqueue() · common/queue.py",
    moves: [["committed", "save>enq", 0.03, 0.25, "queue"], ["SET NX · XADD", "enq>lane", 0.32, 0.72, "queue"]],
    marks: [[0.72, { slots: { lane: ["POL-AML"] },
                     log: [["redis", "SET rci:queued:company_id=1:policy_id=11:type=policy.check 1 NX EX 86400 → OK", "A mark in Redis: “check policy 11 is queued”, so the same check can't be queued twice. It expires after a day."],
                           ["redis", "XADD rci:tasks MAXLEN ~ 100000 * type policy.check company_id 1 policy_id 11", "A note on the main lane: check policy 11 for company 1. A free worker picks it up within moments."]] }]],
  },
  {
    story: 1, dur: 6000, focus: ["enq", "resp", "page"],
    title: "201 Created",
    text: "The api answers 201 with the saved policy, and its page says Waiting for the worker. The api never calls OCR or Gemini itself: it only queues.",
    code: "create_policy() · api/routes/policies.py · watchWorker() · frontend/js/views/policies.js",
    moves: [["201", "enq>resp", 0.03, 0.28, "ok"], ["201 Created", "resp>nginx", 0.33, 0.6, "ok"],
            ["POL-AML", "nginx>page", 0.65, 0.92, "ok"]],
    marks: [
      [0.28, { log: ["http", "INFO \"POST /policies HTTP/1.1\" 201 Created", "The api's own log line: the request worked and created something (201 Created)."] }],
      [0.92, { sub: { page: "POL-AML · Waiting…", poll: "every 3 s" } }],
    ],
  },
  {
    story: 1, dur: 6400, focus: ["lane", "worker", "pg"],
    title: "A worker checks it",
    text: "A worker takes policy.check at once: it turns POL-AML into numbers, checks it against company 1's recent circulars and stamps checked_at.",
    code: "check_policy() · worker/pipeline.py (the Worker tab has it in detail)",
    moves: [["policy.check", "lane>worker", 0.03, 0.3, "queue"], ["checked_at", "worker>pg", 0.62, 0.92, "ok"]],
    marks: [
      [0.03, { slots: { lane: [] } }],
      [0.3, { sub: { worker: "checking POL-AML" } }],
      [0.6, { log: [["log", "INFO embedded POL-AML (1 chunks) with gemini-embedding-001", "A worker turned the policy into numbers. It's short, so it's one piece."], ["log", "INFO POL-AML checked, gaps opened: none", "The worker's summary: the policy is checked against recent circulars, and no gaps were needed."]] }],
      [0.92, { sub: { worker: "waiting", pg: "POL-AML v1 · checked" } }],
    ],
  },
  {
    story: 1, dur: 7000, focus: ["poll", "nginx", "handler", "page"],
    title: "The page notices",
    text: "While it says Waiting, the page asks GET /api/policies/11 every 3 seconds. Once checked_at is newer than updated_at, it shows Checked and a toast.",
    code: "watchWorker(), checked() · frontend/js/views/policies.js",
    moves: [
      ["GET /policies/11", "poll>nginx", 0.02, 0.18, "start"], ["GET", "nginx>app", 0.2, 0.32, "start"],
      ["get_policy()", "app>handler", 0.34, 0.44, "svc"], ["SELECT", "handler>pg", 0.46, 0.56, "data"],
      ["checked_at", "pg>handler", 0.58, 0.68, "data"], ["200", "handler>resp", 0.7, 0.78, "ok"],
      ["200", "resp>nginx", 0.8, 0.88, "ok"], ["Checked", "nginx>page", 0.9, 0.98, "ok"],
    ],
    marks: [
      [0.34, { sub: { handler: "get_policy()" } }],
      [0.56, { log: ["sql", "SELECT * FROM policies WHERE id = 11 AND company_id = 1 → checked_at 10:02:41, updated_at 10:02:38", "The page's 3-second check: checked_at is now later than updated_at, so the worker is done and the page shows Checked."] }],
      [0.98, { sub: { page: "POL-AML · Checked ✓", poll: "off" }, log: ["app", "toast: POL-AML checked by the worker", "The page has been asking every 3 seconds. Now it sees the check is done and shows this message."] }],
    ],
  },

  // ── Story 3: other changes, and Redis down ──
  {
    story: 2, dur: 7200, focus: ["handler", "save", "pg", "lane"],
    title: "Edit a policy",
    text: "PUT /api/policies/11. A text change raises the version, clears the embeddings and notes v2 on the policy's open gaps. Every save queues policy.check.",
    code: "update_policy() · api/routes/policies.py",
    moves: [
      ["PUT /policies/11", "page>nginx", 0.02, 0.15, "start"], ["PUT", "nginx>app", 0.17, 0.28, "start"],
      ["update_policy()", "app>handler", 0.3, 0.4, "svc"], ["v2", "handler>save", 0.42, 0.52, "svc"],
      ["UPDATE", "save>pg", 0.54, 0.68, "data"], ["committed", "save>enq", 0.7, 0.78, "queue"],
      ["policy.check", "enq>lane", 0.8, 0.95, "queue"],
    ],
    marks: [
      [0.3, { sub: { handler: "update_policy()", page: "POL-AML · edit" } }],
      [0.68, { sub: { pg: "POL-AML v2 · re-embed" },
               log: [["sql", "UPDATE policies SET text = '…', version = 2, embeddings = NULL, updated_at = now() WHERE id = 11", "Editing the text makes version 2. Its old numbers are cleared, so the worker will compute new ones."],
                     ["sql", "INSERT INTO gap_events (gap_id, actor, action, note) VALUES (…, 'system', 'policy_updated', 'POL-AML updated to v2')  (each open gap)", "Each of the policy's open gaps gets a history line saying the policy changed, so its owner knows."],
                     ["sql", "COMMIT", "Postgres saves everything so far for good, all together. Until this line nothing was saved, so a failure would have undone it all."]] }],
      [0.95, { slots: { lane: ["POL-AML"] }, log: ["redis", "XADD rci:tasks * type policy.check company_id 1 policy_id 11", "When a policy is saved, the api puts a note on the main lane: check policy 11 for company 1."] }],
    ],
  },
  {
    story: 2, dur: 7200, focus: ["handler", "save", "pg", "lane"],
    title: "Change the description",
    text: "PUT /api/company. Only a new or changed description queues company.refresh, and the answer says checking: true. A new name alone queues nothing.",
    code: "set_company() · api/routes/company.py",
    moves: [
      ["PUT /company", "page>nginx", 0.02, 0.15, "start"], ["PUT", "nginx>app", 0.17, 0.28, "start"],
      ["set_company()", "app>handler", 0.3, 0.4, "svc"], ["profile", "handler>save", 0.42, 0.52, "svc"],
      ["UPDATE", "save>pg", 0.54, 0.68, "data"], ["committed", "save>enq", 0.7, 0.78, "queue"],
      ["company.refresh", "enq>lane", 0.8, 0.95, "queue"],
    ],
    marks: [
      [0.02, { slots: { lane: [] } }],
      [0.3, { sub: { handler: "set_company()", page: "Company · Save" } }],
      [0.68, { sub: { pg: "company 1 · described" },
               log: [["sql", "UPDATE companies SET profile = '…', updated_at = now() WHERE id = 1", "The company's new description is saved."], ["sql", "COMMIT", "Postgres saves everything so far for good, all together. Until this line nothing was saved, so a failure would have undone it all."]] }],
      [0.95, { slots: { lane: ["refresh 1"] },
               log: [["redis", "XADD rci:tasks * type company.refresh company_id 1", "A company.refresh note is queued, so recent circulars are judged again against the new description."], ["http", "200 OK  {\"company\": {…}, \"checking\": true}", "The answer: the description is saved, and the circulars are being checked again."]] }],
    ],
  },
  {
    story: 2, dur: 6800, focus: ["handler", "pg"],
    title: "Work a gap",
    text: "PATCH /api/gaps/{id} changes the status, owner or due date. Each change adds a gap_events line under your email; closing needs a note. Nothing is queued.",
    code: "update_gap() · api/routes/gaps.py",
    moves: [
      ["company.refresh", "lane>worker", 0.02, 0.22, "queue"],
      ["PATCH /gaps/5", "page>nginx", 0.02, 0.18, "start"], ["PATCH", "nginx>app", 0.2, 0.32, "start"],
      ["update_gap()", "app>handler", 0.34, 0.46, "svc"], ["UPDATE + event", "handler>pg", 0.5, 0.72, "data"],
      ["200", "handler>resp", 0.76, 0.86, "ok"], ["200", "resp>nginx", 0.88, 0.96, "ok"],
    ],
    marks: [
      [0.02, { slots: { lane: [] } }],
      [0.22, { sub: { worker: "refreshing company 1" } }],
      [0.34, { sub: { handler: "update_gap()", page: "Gaps · gap 5" } }],
      [0.9, { sub: { worker: "waiting" } }],
      [0.72, { sub: { pg: "gap 5 · in_progress" },
               log: [["sql", "UPDATE gaps SET status = 'in_progress', updated_at = now() WHERE id = 5 AND company_id = 1", "The gap's status becomes in progress. The company_id part makes sure you can only change your own company's gaps."],
                     ["sql", "INSERT INTO gap_events (gap_id, actor, action, note) VALUES (5, 'you@company.com', 'status', 'open -> in_progress')", "A history line records who changed what: you moved it from open to in progress."],
                     ["sql", "COMMIT", "Postgres saves everything so far for good, all together. Until this line nothing was saved, so a failure would have undone it all."]] }],
    ],
  },
  {
    story: 2, dur: 7600, focus: ["save", "enq", "pg", "resp", "page"],
    title: "Redis is down",
    text: "If the task can't be queued, the new policy is deleted again and the answer is 503: nothing was saved, try again. Nothing is ever saved without its task.",
    code: "enqueue_or_undo() · api/database.py",
    moves: [
      ["INSERT", "save>pg", 0.02, 0.18, "data"], ["committed", "save>enq", 0.2, 0.28, "queue"],
      ["XADD ✗", "enq>lane", 0.3, 0.44, "bad"], ["undo", "enq>save", 0.48, 0.58, "bad"],
      ["DELETE", "save>pg", 0.6, 0.72, "bad"], ["503", "enq>resp", 0.75, 0.84, "bad"],
      ["503", "resp>nginx", 0.86, 0.92, "bad"], ["try again", "nginx>page", 0.93, 0.99, "bad"],
    ],
    marks: [
      [0.02, { sub: { handler: "create_policy()", page: "Policies · New policy" } }],
      [0.18, { sub: { pg: "POL-SAN v1 · id 12" }, log: [["sql", "INSERT INTO policies (…) VALUES (1, 'POL-SAN', …) → id 12", "The new policy POL-SAN is saved as usual…"], ["sql", "COMMIT", "Postgres saves everything so far for good, all together. Until this line nothing was saved, so a failure would have undone it all."]] }],
      [0.44, { log: ["redis", "SET rci:queued:company_id=1:policy_id=12:type=policy.check … → Error 111: Connection refused", "The api tries to set the mark in Redis, but Redis doesn't answer (error 111: connection refused)."] }],
      [0.72, { sub: { pg: "POL-SAN deleted again" }, log: [["sql", "DELETE FROM policies WHERE id = 12", "…but Redis can't take its task, so the policy is deleted again. Nothing is saved without its task."], ["sql", "COMMIT", "Postgres saves everything so far for good, all together. Until this line nothing was saved, so a failure would have undone it all."]] }],
      [0.99, { sub: { page: "503 · try again" },
               log: ["http", "503 Service Unavailable  {\"detail\": \"The task queue is unavailable, so nothing was saved: try again\"}", "The api answers 503 with a plain message, and the page shows it: try again once Redis is back."] }],
    ],
  },
];

export default {
  id: "api",
  tab: "API",
  hint: "the console's backend",
  heading: "The api, in detail",
  lead: "What happens when you use the console: signing in, then one policy saved from the button to the worker and back, every hop through nginx, the token check, the body check, the database and the queue. Then edits, gaps, and what happens when Redis is down.",
  label: "The api: the console page sends requests through nginx to FastAPI, which checks the login token and the body, runs the route handler, saves to Postgres and only after the commit queues a task in Redis for a worker, then answers; the page polls until the worker has checked the policy.",
  size: [1240, 620],
  groups: [[16, 40, 246, 532, "your browser"], [290, 196, 154, 172, "frontend container"],
           [480, 40, 498, 556, "the api · FastAPI on uvicorn :8000"], [1004, 40, 216, 556, "behind it"]],
  nodes,
  edges,
  quietEdges: true,
  backbone: ["page>nginx", "nginx>app", "app>auth", "auth>handler", "handler>save", "save>enq", "enq>lane", "lane>worker", "resp>nginx"],
  stories: ["Story 1 · Signing in", "Story 2 · Saving a new policy", "Story 3 · Other changes, and Redis down"],
  steps,
};
