/** The whole system: one circular from the regulator's site to a gap on the Gaps page, then
 * a saved policy being checked. The watcher, the reader, the workers and the console link
 * to their own detailed scenes. */
import { geometry, node } from "./player.js";

const nodes = {
  reg: node(95, 150, 150, 74, "ext", "RBI · SEBI · IRDAI", "regulators' sites"),
  watcher: node(300, 150, 150, 74, "svc", "watcher", "every 60 minutes", { link: "watcher" }),
  s3: node(545, 44, 180, 56, "data", "S3", "the PDFs"),
  pdf: node(545, 150, 250, 92, "queue", "PDF lane", "Redis · rci:tasks:pdf", { slots: 3, mono: true }),
  reader: node(820, 150, 160, 74, "svc", "reader", "waiting", { idle: "waiting", link: "worker" }),
  ocr: node(1075, 150, 150, 74, "gpu", "OCR", "GPU · page by page"),
  db: node(545, 335, 210, 74, "data", "Postgres", "every result"),
  gemini: node(1075, 410, 150, 74, "ext", "Gemini", "questions → answers"),
  team: node(95, 545, 150, 74, "start", "your team", "in the browser"),
  console: node(300, 545, 150, 74, "svc", "console + api", "Gaps · Policies", { badge: true, link: "api" }),
  main: node(545, 545, 250, 92, "queue", "main lane", "Redis · rci:tasks", { slots: 3, mono: true }),
  w1: node(840, 480, 160, 66, "svc", "worker 1", "waiting", { idle: "waiting", link: "worker" }),
  w2: node(840, 610, 160, 66, "svc", "worker 2", "waiting", { idle: "waiting", link: "worker" }),
};

const { at, line, curve } = geometry(nodes);

const edges = {
  "reg>watcher": line(at("reg", "r"), at("watcher", "l")),
  "watcher>s3": curve(at("watcher", "t"), [300, 44], [380, 44], at("s3", "l")),
  "watcher>pdf": line(at("watcher", "r"), at("pdf", "l")),
  "watcher>db": curve(at("watcher", "b"), [300, 320], [380, 323], at("db", "l", -12)),
  "s3>reader": curve(at("s3", "r"), [790, 44], [820, 70], at("reader", "t")),
  "pdf>reader": line(at("pdf", "r"), at("reader", "l")),
  "reader>ocr": line(at("reader", "r"), at("ocr", "l")),
  "reader>gemini": curve(at("reader", "b", 50), [870, 320], [950, 395], at("gemini", "l", -15)),
  "reader>db": curve(at("reader", "b", -50), [770, 290], [700, 323], at("db", "r", -12)),
  "reader>main": curve(at("reader", "b", -10), [810, 400], [700, 470], at("main", "t", 95)),
  "team>console": line(at("team", "r"), at("console", "l")),
  "console>main": line(at("console", "r"), at("main", "l")),
  "console>db": curve(at("console", "t", 30), [330, 420], [380, 347], at("db", "l", 12)),
  "main>w1": curve(at("main", "r", -12), [720, 533], [720, 480], at("w1", "l")),
  "main>w2": curve(at("main", "r", 12), [720, 557], [720, 610], at("w2", "l")),
  "w1>gemini": curve(at("w1", "r"), [960, 480], [960, 420], at("gemini", "l", 10)),
  "w2>gemini": curve(at("w2", "r"), [1075, 610], [1075, 520], at("gemini", "b")),
  "w1>db": curve(at("w1", "t", -50), [790, 380], [710, 347], at("db", "r", 12)),
  "w2>db": curve(at("w2", "t", -60), [740, 500], [640, 430], at("db", "b", 60)),
};

const steps = [
  {
    story: 0, dur: 4200, focus: ["reg", "watcher"],
    title: "The watcher finds it",
    text: "Every 60 minutes the watcher reads the regulators' lists. Circular 98 is one it has never seen, so it downloads the PDF.",
    code: "run_source(), fetch_new() · watcher/main.py",
    moves: [["circular 98", "reg>watcher", 0.08, 0.7, "ext"]],
  },
  {
    story: 0, dur: 4800, focus: ["watcher"],
    title: "It saves the PDF and a row",
    text: "The PDF goes to S3, named by its fingerprint, and a row goes to Postgres with status new. A circular is never saved twice.",
    code: "fetch_new() · watcher/main.py · put_pdf() · watcher/storage.py",
    moves: [["PDF", "watcher>s3", 0.05, 0.55, "data"], ["row 98", "watcher>db", 0.25, 0.75, "data"]],
    marks: [[0.75, { sub: { db: "circular 98 · new" } }]],
  },
  {
    story: 0, dur: 4500, focus: ["watcher", "pdf"],
    title: "A note on the PDF lane",
    text: "It queues a small task, read 98: just a type and an id. Reading a PDF takes minutes, so PDFs have a lane of their own.",
    code: "enqueue() · common/queue.py",
    moves: [["read 98", "watcher>pdf", 0.1, 0.6, "queue"]],
    marks: [[0.6, { slots: { pdf: ["read 98"] }, log: ["log", "INFO RBI new: Designation of terrorist organisation under clause (a) …"] }]],
  },
  {
    story: 0, dur: 4500, focus: ["pdf", "reader"],
    title: "The reader takes it at once",
    text: "Redis hands the note to the one reader and writes the reader's name on it, so nobody else can take it.",
    code: "next_task() · worker/main.py",
    moves: [["read 98", "pdf>reader", 0.12, 0.6, "queue"]],
    marks: [[0.12, { slots: { pdf: [] } }], [0.6, { sub: { reader: "reading 98" } }]],
  },
  {
    story: 0, dur: 7000, focus: ["reader", "ocr"],
    title: "OCR reads each page once",
    text: "The reader fetches the PDF from S3 and sends it to OCR a page at a time. Each page's text is saved the moment it's read.",
    code: "ocr_text() · worker/pipeline.py · pages() · worker/ocr.py",
    moves: [
      ["PDF", "s3>reader", 0.02, 0.18, "data"],
      ["page 1", "reader>ocr", 0.2, 0.34, "gpu"], ["text", "ocr>reader", 0.36, 0.5, "gpu"],
      ["page 2", "reader>ocr", 0.52, 0.66, "gpu"], ["text", "ocr>reader", 0.68, 0.8, "gpu"],
      ["text", "reader>db", 0.8, 0.94, "data"],
    ],
    marks: [[0.94, { sub: { db: "circular 98 · text saved" }, log: ["log", "INFO #98 parsed: 2431 chars"] }]],
  },
  {
    story: 0, dur: 5600, focus: ["reader", "gemini"],
    title: "Gemini sums it up",
    text: "Who it's addressed to, a short summary and every obligation. The summary also becomes numbers, used to find close policies.",
    code: "summarize(), embed() · worker/llm.py",
    moves: [
      ["summarise", "reader>gemini", 0.05, 0.38, "ext"], ["summary", "gemini>reader", 0.44, 0.74, "ext"],
      ["summary", "reader>db", 0.76, 0.92, "data"],
    ],
    marks: [[0.92, { sub: { db: "circular 98 · read" },
                     log: ["log", "INFO #98 read: addressed to 'The Chairpersons/ CEOs of the Commercial Banks, …'"] }]],
  },
  {
    story: 0, dur: 5200, focus: ["reader", "main"],
    title: "One check per company",
    text: "Each company gets its own note on the main lane: check 98 for company A, and for company B. The reader is done with 98.",
    code: "add_assessments(), pending() · worker/pipeline.py",
    moves: [["check 98·A", "reader>main", 0.05, 0.5, "queue"], ["check 98·B", "reader>main", 0.25, 0.7, "queue"]],
    marks: [[0.5, { slots: { main: ["98·A"] } }], [0.7, { slots: { main: ["98·A", "98·B"] } }],
            [0.8, { sub: { reader: "waiting" } }]],
  },
  {
    story: 0, dur: 5800, focus: ["main", "w1", "w2"],
    title: "Two workers, one note each",
    text: "Each note goes to exactly one worker, so A and B are checked at the same time. Meanwhile the reader starts on circular 99.",
    code: "serve(), next_task() · worker/main.py",
    moves: [
      ["98·A", "main>w1", 0.1, 0.5, "queue"], ["98·B", "main>w2", 0.15, 0.55, "queue"],
      ["read 99", "watcher>pdf", 0.05, 0.42, "queue"], ["read 99", "pdf>reader", 0.5, 0.8, "queue"],
    ],
    marks: [
      [0.1, { slots: { main: ["98·B"] } }], [0.15, { slots: { main: [] } }],
      [0.42, { slots: { pdf: ["read 99"] } }], [0.5, { slots: { pdf: [] }, sub: { w1: "checking 98·A" } }],
      [0.55, { sub: { w2: "checking 98·B" } }], [0.8, { sub: { reader: "reading 99" } }],
    ],
  },
  {
    story: 0, dur: 5800, focus: ["w1", "w2", "gemini"],
    title: "Does it apply?",
    text: "Gemini compares each company's description with who the circular is for: yes for A, an NBFC; no for B, a stock broker.",
    code: "assess() · worker/pipeline.py · check_applicability() · worker/llm.py",
    moves: [
      ["applies?", "w1>gemini", 0.05, 0.4, "ext"], ["applies?", "w2>gemini", 0.1, 0.45, "ext"],
      ["yes", "gemini>w1", 0.5, 0.85, "ok"], ["no", "gemini>w2", 0.55, 0.9, "ext"],
      ["page 1", "reader>ocr", 0.2, 0.45, "gpu"], ["text", "ocr>reader", 0.55, 0.8, "gpu"],
    ],
    marks: [[0.85, { sub: { w1: "98 applies to A" } }], [0.9, { sub: { w2: "98: not for B" } }]],
  },
  {
    story: 0, dur: 5800, focus: ["w1", "gemini"],
    title: "Is a close policy out of date?",
    text: "Worker 1 scores A's policies against the circular, plain arithmetic, and asks Gemini about the closest. POL-KYC is out of date.",
    code: "match(), judge_policy() · worker/pipeline.py",
    moves: [
      ["POL-KYC?", "w1>gemini", 0.05, 0.4, "ext"], ["out of date", "gemini>w1", 0.5, 0.85, "gap"],
      ["B: done", "w2>db", 0.2, 0.55, "data"],
    ],
    marks: [[0.55, { sub: { w2: "waiting" }, log: ["log", "INFO #98 for company 2: applies: False, gaps opened: none"] }],
            [0.85, { sub: { w1: "POL-KYC out of date" } }]],
  },
  {
    story: 0, dur: 5400, focus: ["w1", "db", "console", "team"],
    title: "A gap for the policy's owner",
    text: "The verdict and a gap with a draft fix are saved together, due in 7 days. It shows on company A's Gaps page only.",
    code: "judge_policy() · worker/pipeline.py",
    moves: [["gap", "w1>db", 0.05, 0.4, "gap"], ["gap", "db>console", 0.45, 0.8, "gap"]],
    marks: [[0.4, { sub: { db: "gap opened · POL-KYC" }, log: ["log", "INFO #98 vs POL-KYC v1 (0.82): GAP"] }],
            [0.8, { badge: { console: 1 }, sub: { console: "1 new gap", w1: "waiting" },
                    log: ["log", "INFO #98 for company 1: applies: True, gaps opened: ['POL-KYC']"] }]],
  },
  {
    story: 0, dur: 4200, focus: ["main", "w1", "w2"],
    title: "Finished, never twice",
    text: "Each worker tells Redis it's finished (XACK), and its note leaves the list for good. Work that's saved is never done again.",
    code: "run_task() · worker/main.py",
    moves: [["XACK", "w1>main", 0.1, 0.5, "ok"], ["XACK", "w2>main", 0.15, 0.55, "ok"]],
  },
  {
    story: 1, dur: 5800, focus: ["team", "console", "main"],
    title: "You save a policy",
    text: "The api saves POL-AML in Postgres first, then queues policy.check on the main lane. Its page says Waiting for the worker.",
    code: "create_policy() · api/routes/policies.py",
    moves: [
      ["POL-AML", "team>console", 0.05, 0.3, "start"], ["policy", "console>db", 0.32, 0.58, "data"],
      ["check POL-AML", "console>main", 0.6, 0.88, "queue"],
    ],
    marks: [[0.3, { sub: { console: "POL-AML: waiting" } }], [0.58, { sub: { db: "POL-AML · saved" } }],
            [0.88, { slots: { main: ["POL-AML"] } }]],
  },
  {
    story: 1, dur: 6400, focus: ["w1", "gemini", "console"],
    title: "A worker checks it at once",
    text: "It turns the policy into numbers, then checks it against your circulars of the last 30 days. The page now says Checked.",
    code: "check_policy() · worker/pipeline.py",
    moves: [
      ["POL-AML", "main>w1", 0.04, 0.28, "queue"], ["embed", "w1>gemini", 0.3, 0.48, "ext"],
      ["numbers", "gemini>w1", 0.5, 0.66, "ext"], ["checked", "w1>db", 0.7, 0.84, "ok"],
      ["Checked", "db>console", 0.86, 0.97, "ok"],
    ],
    marks: [[0.04, { slots: { main: [] } }], [0.28, { sub: { w1: "checking POL-AML" } }],
            [0.84, { sub: { db: "POL-AML · checked" },
                     log: [["log", "INFO embedded POL-AML (1 chunks) with gemini-embedding-001"],
                           ["log", "INFO POL-AML checked, gaps opened: none"]] }],
            [0.97, { sub: { console: "POL-AML: Checked", w1: "waiting" } }]],
  },
];

export default {
  id: "system",
  tab: "Whole system",
  hint: "one circular, end to end",
  heading: "The whole system, step by step",
  lead: "Follow one circular from a regulator's website to a gap on your Gaps page, then a policy you save. Each part is its own service: they only pass small notes, called tasks, through Redis. Click the watcher, the reader, a worker or the console to see that part in detail.",
  label: "The system: the watcher saves new circulars and puts a note on the PDF lane; the reader reads each PDF with OCR and Gemini and puts one note per company on the main lane; the workers check each company's policies with Gemini and open gaps, which your team sees in the console.",
  size: [1180, 680],
  nodes,
  edges,
  stories: ["Story 1 · A new circular arrives", "Story 2 · You save a policy"],
  steps,
};
