/** The watcher in detail, as in how_the_watcher_works.md: one round step by step with its
 * example (RBI circular 98), the three regulators one by one, being polite, every way a
 * round can go wrong, and what happens next. The nine numbered boxes are the guide's nine
 * steps; under the picture, the rows each step changes, and the log, SQL and requests. */
import { geometry, node } from "./player.js";

const IDLE_FETCH = "1.5 s pause · 3 tries";
const W = "waiting";

const nodes = {
  rss: node(135, 100, 220, 60, "ext", "RBI · RSS feed", "about 10 newest"),
  rbipage: node(135, 180, 220, 60, "ext", "RBI · a circular's page", "NotificationUser.aspx?Id=…", { mono: true }),
  rbidocs: node(135, 260, 220, 60, "ext", "RBI · its PDF server", "rbidocs.rbi.org.in", { mono: true }),
  sebi: node(135, 380, 220, 60, "ext", "SEBI · 3 listing pages", "25 newest on each"),
  irdai: node(135, 480, 220, 60, "ext", "IRDAI · circulars table", "each row links its PDF"),

  fetch: node(365, 300, 150, 120, "svc", "fetch.py", IDLE_FETCH, { idle: IDLE_FETCH }),
  fail: node(365, 560, 150, 72, "bad", "nothing kept", "retried next round"),

  s1: node(620, 90, 270, 52, "start", "wake up", "a round every 60 min", { num: 1 }),
  s2: node(620, 160, 270, 52, "svc", "get each list", "sources.py", { num: 2 }),
  s3: node(620, 230, 270, 52, "ask", "skip the known ones", "one query per regulator", { num: 3 }),
  s4: node(620, 300, 270, 52, "svc", "find the PDF link", "resolve_pdf_url()", { num: 4, mono: true }),
  s5: node(620, 370, 270, 52, "ask", "download, check it", "starts with %PDF?", { num: 5 }),
  s6: node(620, 440, 270, 52, "data", "fingerprint → S3", "sha256 of the bytes", { num: 6 }),
  s7: node(620, 510, 270, 52, "data", "add a row", "circulars, status new", { num: 7 }),
  s8: node(620, 580, 270, 52, "queue", "queue a task", "a mark, then the lane", { num: 8 }),
  s9: node(620, 650, 270, 52, "ok", "summary, then sleep", "one line per regulator", { num: 9 }),

  s3obj: node(985, 100, 330, 60, "data", "S3 · bucket rci", "one file per fingerprint"),
  pg: node(985, 220, 330, 70, "data", "Postgres · circulars", "UNIQUE (source, source_key)"),
  marks: node(985, 340, 330, 60, "queue", "Redis · marks", "none", { mono: true }),
  lane: node(985, 452, 330, 92, "queue", "Redis · PDF lane", "rci:tasks:pdf", { slots: 3, mono: true }),
  reader: node(985, 590, 330, 64, "svc", "reader", W, { idle: W, link: "worker" }),
};

const { at, line, curve } = geometry(nodes);

const edges = {
  "s1>s2": line(at("s1", "b"), at("s2", "t")),
  "s2>s3": line(at("s2", "b"), at("s3", "t")),
  "s3>s4": line(at("s3", "b"), at("s4", "t")),
  "s4>s5": line(at("s4", "b"), at("s5", "t")),
  "s5>s6": line(at("s5", "b"), at("s6", "t")),
  "s6>s7": line(at("s6", "b"), at("s7", "t")),
  "s7>s8": line(at("s7", "b"), at("s8", "t")),
  "s8>s9": line(at("s8", "b"), at("s9", "t")),
  "s9>s1": curve(at("s9", "r"), [790, 650], [790, 90], at("s1", "r")),
  "s2>fetch": curve(at("s2", "l"), [460, 150], [460, 270], at("fetch", "r", -30)),
  "s4>fetch": curve(at("s4", "l"), [462, 290], [462, 300], at("fetch", "r")),
  "s5>fetch": curve(at("s5", "l"), [462, 360], [462, 330], at("fetch", "r", 30)),
  "fetch>rss": curve(at("fetch", "l", -40), [268, 260], [268, 100], at("rss", "r")),
  "fetch>rbipage": curve(at("fetch", "l", -20), [270, 280], [270, 180], at("rbipage", "r")),
  "fetch>rbidocs": curve(at("fetch", "l"), [272, 300], [272, 260], at("rbidocs", "r")),
  "fetch>sebi": curve(at("fetch", "l", 20), [270, 320], [270, 380], at("sebi", "r")),
  "fetch>irdai": curve(at("fetch", "l", 40), [268, 340], [268, 480], at("irdai", "r")),
  "fetch>fail": line(at("fetch", "b"), at("fail", "t")),
  "s3>pg": line(at("s3", "r"), at("pg", "l")),
  "s6>s3obj": curve(at("s6", "r", -10), [786, 420], [786, 100], at("s3obj", "l")),
  "s7>pg": curve(at("s7", "r"), [792, 500], [792, 232], at("pg", "l", 12)),
  "s8>marks": curve(at("s8", "r"), [794, 570], [794, 345], at("marks", "l", 5)),
  "marks>lane": line(at("marks", "b"), at("lane", "t")),
  "lane>reader": line(at("lane", "b"), at("reader", "t")),
  "s4>fail": curve(at("s4", "l", 14), [454, 304], [454, 548], at("fail", "r", -12)),
  "s5>fail": curve(at("s5", "l", 14), [458, 374], [458, 556], at("fail", "r", -4)),
  "s6>fail": curve(at("s6", "l", 10), [460, 440], [460, 564], at("fail", "r", 4)),
  "s8>fail": curve(at("s8", "l"), [462, 570], [462, 572], at("fail", "r", 12)),
};

const tables = {
  items: { title: "RBI's list, as items", store: "sources.py", cols: ["source_key", "title", "published_at", "known?"] },
  rules: { title: "fetch.py's rules", store: "watcher/fetch.py", cols: ["rule", "why"] },
  links: { title: "PDF links on the circular's page", store: "resolve_pdf_url()", cols: ["link", "taken?"] },
  s3: { title: "S3", store: "Floci on your machine", cols: ["bucket", "key", "type"] },
  circulars: { title: "circulars", store: "Postgres", cols: ["id", "source", "source_key", "title", "sha256", "s3_key", "status"] },
  redis: { title: "Redis", store: "Redis", cols: ["what", "value"] },
  regulators: { title: "the three regulators", store: "sources.py", cols: ["regulator", "read from", "how many", "the PDF link"] },
  failures: { title: "when something goes wrong", store: "all or nothing", cols: ["what happened", "in the log", "what happens next", "what to do"] },
};

const ROW_98 = ["98", "RBI", "id=13650", "Designation of terrorist organisation…", "3f9a…c1", "rbi/3f9a…c1.pdf", "new"];
const ITEM_98 = ["id=13650", "Designation of terrorist organisation…", "2026-10-01 09:30 IST"];
const ITEMS = (k98, k49, k48, rest) => [[...ITEM_98, k98], ["id=13649", "(an earlier circular)", "2026-09-30", k49],
                                         ["id=13648", "(an earlier circular)", "2026-09-29", k48], ["…", "7 more", "", rest]];
const PDF = "https://rbidocs.rbi.org.in/rdocs/notification/PDFs/NT98DESIGNATION.PDF";
const FAIL = {
  down: ["a regulator's site is down", "SEBI: listing failed: …", "the next round tries again", "nothing"],
  layout: ["the site changed its layout", "… page layout may have changed", "every round fails the same way", "update that reader in sources.py"],
  nolink: ["a circular's page has no PDF link", "RBI failed (…): no PDF link on …", "tried again every round", "nothing, unless it lasts"],
  html: ["the download is an HTML page", "… failed (…): not a PDF: …", "tried again next round", "nothing"],
  floci: ["Floci (S3) isn't running", "… Could not connect to the endpoint URL: …", "nothing saved; tried every round", "floci start --persist=\"$HOME/.floci/aws-state\""],
  redis: ["Redis is down", "RBI failed (…): Error 111 connecting to redis:6379", "the row is deleted again; tried every round", "docker compose up -d redis"],
  postgres: ["Postgres is down", "the watcher restarts until it's back", "the next round catches up", "docker compose up -d"],
};

const steps = [
  // ── One round, step by step ──
  {
    story: 0, ref: "step 1", dur: 6600, focus: ["s1"], tables: [],
    title: "Wake up",
    text: "The watcher is a loop: one round, then 60 minutes of sleep, forever. The first round starts when its container starts. Run by hand it does one round and stops; --only RBI does one regulator.",
    code: "main() · watcher/main.py · WATCH_INTERVAL_MINUTES in .env",
    moves: [["round: RBI first", "s1>s2", 0.45, 0.85, "start"]],
    marks: [[0.2, { sub: { s1: "round starts: RBI first" } }]],
  },
  {
    story: 0, ref: "step 2", dur: 7400, focus: ["s2", "fetch", "rss"], tables: [],
    title: "Ask for RBI's list",
    text: "Each regulator publishes its list differently, so each has its own small reader in sources.py. RBI's reads its notifications RSS feed: about the 10 newest.",
    code: "rbi(), rss_items() · watcher/sources.py",
    moves: [["the feed's address", "s2>fetch", 0.03, 0.22, "svc"], ["GET", "fetch>rss", 0.36, 0.52, "ext"],
            ["XML", "rss>fetch", 0.56, 0.72, "ext"], ["XML", "fetch>s2", 0.76, 0.95, "svc"]],
    marks: [
      [0.22, { sub: { fetch: "waiting 1.5 s…" } }],
      [0.36, { sub: { fetch: "GET the RSS feed" } }],
      [0.52, { log: ["http", "GET https://www.rbi.org.in/notifications_rss.xml → 200 OK"] }],
      [0.95, { sub: { fetch: IDLE_FETCH } }],
    ],
  },
  {
    story: 0, ref: "being polite", dur: 7600, focus: ["fetch"], tables: ["rules"],
    title: "Every request is polite",
    text: "Every request goes through fetch.py, so the watcher never hammers a regulator's site: a pause first, a normal browser's name, a few patient retries, a timeout.",
    code: "get(), retryable(), DELAY · watcher/fetch.py",
    moves: [["pause 1.5 s, then GET", "fetch>rss", 0.25, 0.7, "svc"]],
    marks: [[0.05, { sub: { fetch: "the rules: see below" }, rows: { rules: [
      ["a 1.5-second pause before every request", "regulators' sites are public services: no bursts"],
      ["a normal browser's name (User-Agent)", "RBI's PDF server shows a bot-check page to anything else"],
      ["up to 3 tries on 429, 5xx, network errors: 2 s, then 4 s", "a busy moment shouldn't lose a circular"],
      ["a 30-second timeout; redirects followed", "a stuck site can't stall the whole round"],
    ] } }], [0.95, { sub: { fetch: IDLE_FETCH } }]],
  },
  {
    story: 0, ref: "step 2", dur: 7600, focus: ["s2"], tables: ["items"],
    title: "The list becomes items",
    text: "feedparser reads the feed. Each entry becomes an item: a title, a link, a date and an id from the link. RBI sends its times without a zone, so IST is assumed.",
    code: "rss_items(), stable_key(), entry_date() · watcher/sources.py",
    moves: [],
    marks: [[0.3, { sub: { s2: "RBI: 10 items" }, rows: { items: ITEMS("", "", "", "") } }]],
  },
  {
    story: 0, ref: "step 3", dur: 7600, focus: ["s3", "pg"], tables: ["items"],
    title: "Skip the ones it already knows",
    text: "One question to Postgres per regulator, not one per item: every id it has for RBI. 9 of the 10 are known. Regulator and id together name a circular, so ids never clash.",
    code: "run_source() · watcher/main.py",
    moves: [["10 items", "s2>s3", 0.03, 0.18, "svc"], ["SELECT ids", "s3>pg", 0.24, 0.48, "data"], ["9 known", "pg>s3", 0.54, 0.78, "data"]],
    marks: [
      [0.48, { log: ["sql", "SELECT source_key FROM circulars WHERE source = 'RBI'"] }],
      [0.8, { rows: { items: ITEMS("new", "yes: skip", "yes: skip", "yes: skip") }, sub: { s3: "1 new: id=13650" } }],
    ],
  },
  {
    story: 0, ref: "step 3", dur: 6800, focus: ["s3"], tables: ["items"],
    title: "No date check here",
    text: "Nothing about dates is checked: an old circular it has never seen (on the very first round, say) is saved too. The reader later marks it skipped without reading it.",
    code: "run_source() · watcher/main.py",
    moves: [],
  },
  {
    story: 0, ref: "step 4", dur: 7600, focus: ["s4", "fetch", "rbipage"], tables: [],
    title: "Find the PDF link",
    text: "The item's link is a web page about the circular, not the PDF. The watcher opens that page and looks for the PDF links on it.",
    code: "resolve_pdf_url() · watcher/sources.py",
    moves: [["id=13650", "s3>s4", 0.02, 0.16, "ask"], ["GET the page", "s4>fetch", 0.2, 0.36, "svc"], ["GET", "fetch>rbipage", 0.4, 0.54, "ext"],
            ["HTML", "rbipage>fetch", 0.58, 0.72, "ext"], ["HTML", "fetch>s4", 0.76, 0.92, "svc"]],
    marks: [
      [0.36, { sub: { fetch: "waiting 1.5 s…" } }],
      [0.54, { log: ["http", "GET https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=13650&Mode=0 → 200 OK"] }],
      [0.72, { sub: { fetch: IDLE_FETCH } }],
    ],
  },
  {
    story: 0, ref: "step 4", dur: 7600, focus: ["s4"], tables: ["links"],
    title: "Unwrap it, prefer English",
    text: "A link wrapped in a viewer (…/web/?file=https://site/doc.pdf) is unwrapped. With a Hindi and an English PDF the English one is taken; with only a Hindi one, that one.",
    code: "resolve_pdf_url() · watcher/sources.py",
    moves: [],
    marks: [[0.3, { sub: { s4: "…/NT98DESIGNATION.PDF" }, rows: { links: [
      ["…/PDFs/NT98DESIGNATIONHINDI.PDF", "no: the Hindi one"],
      ["…/PDFs/NT98DESIGNATION.PDF", "yes: the English one"],
    ] } }]],
  },
  {
    story: 0, ref: "step 5", dur: 7400, focus: ["s5", "fetch", "rbidocs"], tables: [],
    title: "Download it",
    text: "fetch.py downloads the file. On a 429, a 5xx or a dropped connection it waits 2 s, then 4 s, and tries again: 3 tries in all.",
    code: "fetch_new() · watcher/main.py · get() · watcher/fetch.py",
    moves: [["PDF link", "s4>s5", 0.02, 0.16, "svc"], ["GET the PDF", "s5>fetch", 0.2, 0.36, "svc"], ["GET", "fetch>rbidocs", 0.4, 0.54, "ext"],
            ["the bytes", "rbidocs>fetch", 0.58, 0.74, "ext"], ["the bytes", "fetch>s5", 0.78, 0.94, "svc"]],
    marks: [
      [0.36, { sub: { fetch: "waiting 1.5 s…" } }],
      [0.54, { log: ["http", `GET ${PDF} → 200 OK`] }],
      [0.74, { sub: { fetch: IDLE_FETCH } }],
    ],
  },
  {
    story: 0, ref: "step 5", dur: 6800, focus: ["s5"], tables: [],
    title: "Is it really a PDF?",
    text: "Some sites answer 200 OK with an HTML error page instead of the file. Every real PDF starts with the characters %PDF, so that's checked before anything is kept.",
    code: "fetch_new() · watcher/main.py",
    moves: [],
    marks: [[0.35, { sub: { s5: "✓ it starts with %PDF" } }]],
  },
  {
    story: 0, ref: "step 6", dur: 7000, focus: ["s6"], tables: [],
    title: "Its fingerprint",
    text: "The sha256 of the bytes: 64 characters that only this exact file gives. The same file always gets the same code; change one byte and it's a different one.",
    code: "fetch_new() · watcher/main.py",
    moves: [["the bytes", "s5>s6", 0.05, 0.3, "data"]],
    marks: [[0.4, { sub: { s6: "sha256: 3f9a…c1" } }]],
  },
  {
    story: 0, ref: "step 6", dur: 7200, focus: ["s6", "s3obj"], tables: ["s3"],
    title: "Store it in S3, named by the fingerprint",
    text: "The file goes to S3 as rbi/3f9a…c1.pdf, a folder per regulator. The same file always gets the same name, so it's never stored twice; the reader uses the fingerprint to spot twins.",
    code: "put_pdf() · watcher/storage.py",
    moves: [["the PDF", "s6>s3obj", 0.1, 0.6, "data"]],
    marks: [[0.6, { rows: { s3: [["rci", "rbi/3f9a…c1.pdf", "application/pdf"]] }, sub: { s3obj: "rbi/3f9a…c1.pdf" },
                    log: ["s3", "PUT s3://rci/rbi/3f9a…c1.pdf (application/pdf)"] }]],
  },
  {
    story: 0, ref: "step 7", dur: 7400, focus: ["s7", "pg"], tables: ["circulars"],
    title: "Add a row in Postgres",
    text: "Only once the PDF is safely in S3: a circulars row, status new, with both links, the date, the fingerprint and the S3 key. Its text and summary stay empty for the reader.",
    code: "fetch_new() · watcher/main.py · Circular · common/models.py",
    moves: [["S3 done", "s6>s7", 0.02, 0.16, "data"], ["INSERT", "s7>pg", 0.22, 0.62, "data"]],
    marks: [[0.62, { rows: { circulars: [ROW_98] }, sub: { pg: "98 · RBI · id=13650 · new" },
                     log: [["sql", "INSERT INTO circulars (source, source_key, title, detail_url, pdf_url, published_at, sha256, s3_key, status) VALUES ('RBI', 'id=13650', 'Designation of terrorist organisation…', …, 'new') → id 98"],
                           ["sql", "COMMIT"]] }]],
  },
  {
    story: 0, ref: "step 7", dur: 6800, focus: ["s6", "s7", "s8"], tables: ["circulars"],
    title: "Nothing half-saved",
    text: "The order is the PDF, then the row, then the task. If the task can't be queued, the row is deleted again: a saved circular always has its PDF and its task.",
    code: "fetch_new() · watcher/main.py",
    moves: [],
  },
  {
    story: 0, ref: "step 8", dur: 7800, focus: ["s8", "marks", "lane"], tables: ["redis"],
    title: "Put a task on the to-do list",
    text: "First a mark, so the same task is never added twice (Reprocess pressed twice, say). Then the task itself, read 98, on the PDF lane: the workers' only source of work.",
    code: "enqueue(), key() · common/queue.py",
    moves: [["row saved", "s7>s8", 0.02, 0.14, "queue"], ["SET mark", "s8>marks", 0.18, 0.48, "queue"], ["XADD read 98", "marks>lane", 0.56, 0.86, "queue"]],
    marks: [
      [0.48, { sub: { marks: "circular_id=98:type=circular.read" },
               rows: { redis: [["mark", "rci:queued:circular_id=98:type=circular.read · gone in a day at most"]] },
               log: ["redis", "SET rci:queued:circular_id=98:type=circular.read 1 NX EX 86400 → OK"] }],
      [0.86, { slots: { lane: ["read 98"] },
               rows: { redis: [["mark", "rci:queued:circular_id=98:type=circular.read · gone in a day at most"],
                               ["PDF lane", "read 98: type circular.read, circular_id 98"]] },
               log: [["redis", "XADD rci:tasks:pdf MAXLEN ~ 100000 * type circular.read circular_id 98"],
                     ["log", "INFO RBI new: Designation of terrorist organisation…"]] }],
    ],
  },
  {
    story: 0, ref: "step 8", dur: 6600, focus: ["lane", "reader"], tables: ["redis"],
    title: "The reader picks it up",
    text: "The reader is waiting on the PDF lane and takes the note within moments. It never looks in Postgres for new circulars: the note is how it knows. Click it to follow.",
    code: "next_task() · worker/main.py",
    moves: [["read 98", "lane>reader", 0.15, 0.65, "queue"]],
    marks: [[0.15, { slots: { lane: [] } }], [0.65, { sub: { reader: "reading 98" } }]],
  },
  {
    story: 0, ref: "step 9", dur: 6400, focus: ["s9"], tables: [],
    title: "RBI's summary line",
    text: "After each regulator, one line in the log: how many items its list had, how many were new, how many failed. Here: seen=10 new=1 failed=0.",
    code: "run_source() · watcher/main.py",
    moves: [["RBI done", "s8>s9", 0.1, 0.4, "ok"]],
    marks: [[0.45, { sub: { s9: "RBI: seen=10 new=1 failed=0" }, log: ["log", "INFO RBI: seen=10 new=1 failed=0"] }]],
  },

  // ── The three regulators, one by one ──
  {
    story: 1, ref: "the regulators", dur: 8400, focus: ["s2", "fetch", "sebi"], tables: ["regulators"],
    title: "SEBI: three listing pages",
    text: "SEBI's RSS feed keeps only its latest 30 items, mostly orders, so it misses circulars. The watcher reads SEBI's three listing pages instead: circulars, master circulars, regulations.",
    code: "sebi() · watcher/sources.py",
    moves: [["SEBI", "s1>s2", 0.02, 0.14, "start"], ["3 pages", "s2>fetch", 0.18, 0.34, "svc"], ["GET ×3", "fetch>sebi", 0.38, 0.56, "ext"],
            ["HTML ×3", "sebi>fetch", 0.6, 0.78, "ext"], ["92 items", "fetch>s2", 0.8, 0.96, "svc"]],
    marks: [
      [0.02, { sub: { s1: "round: SEBI", s2: "SEBI: 92 items", s3: "one query per regulator", s9: "one line per regulator" },
               rows: { regulators: [
                 ["RBI", "its notifications RSS feed", "about 10", "found on each circular's page"],
                 ["SEBI", "3 listing pages: circulars, master circulars, regulations", "25 on each", "found on each circular's page"],
                 ["IRDAI", "its circulars table", "the whole table", "in the row itself"],
               ] } }],
      [0.56, { log: [["http", "GET https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListing=yes&sid=1&smid=0&ssid=7 → 200 OK (circulars)"],
                     ["http", "GET …&ssid=6 → 200 OK (master circulars)"], ["http", "GET …&ssid=3 → 200 OK (regulations)"]] }],
    ],
  },
  {
    story: 1, ref: "the regulators", dur: 7200, focus: ["sebi", "s2"], tables: ["regulators"],
    title: "A regulation's date",
    text: "A regulation's first cell has only a year, so its date comes from \"[Last amended on July 7, 2026]\" in its title. Each SEBI circular's PDF link is found on its own page.",
    code: "sebi_date() · watcher/sources.py",
    moves: [],
  },
  {
    story: 1, ref: "the regulators", dur: 8000, focus: ["s2", "fetch", "irdai"], tables: ["regulators"],
    title: "IRDAI: the circulars table",
    text: "IRDAI has no RSS, so the watcher reads its circulars table. Each row already links its PDF, so step 4 has nothing to look up. Links elsewhere on the page are ignored.",
    code: "irdai() · watcher/sources.py",
    moves: [["IRDAI", "s1>s2", 0.02, 0.14, "start"], ["the table", "s2>fetch", 0.18, 0.34, "svc"], ["GET", "fetch>irdai", 0.38, 0.56, "ext"],
            ["HTML", "irdai>fetch", 0.6, 0.78, "ext"], ["20 items", "fetch>s2", 0.8, 0.96, "svc"]],
    marks: [
      [0.02, { sub: { s1: "round: IRDAI", s2: "IRDAI: 20 items" } }],
      [0.56, { log: ["http", "GET https://irdai.gov.in/circulars → 200 OK"] }],
    ],
  },
  {
    story: 1, ref: "the regulators", dur: 7600, focus: ["s2", "fail"], tables: ["failures"],
    title: "Nothing found? The layout changed",
    text: "If a reader finds no circulars at all, it stops with \"page layout may have changed\": the regulator redesigned its site, and that reader in sources.py needs updating.",
    code: "sebi(), irdai() · watcher/sources.py",
    moves: [["no links found", "fetch>fail", 0.2, 0.7, "bad"]],
    marks: [[0.02, { rows: { failures: [FAIL.layout] } }], [0.7, { sub: { fail: "layout changed?" },
                    log: ["error", "ERROR IRDAI: listing failed: IRDAI: no circular links found; page layout may have changed"] }]],
  },
  {
    story: 1, ref: "step 9", dur: 7400, focus: ["s9", "s1"], tables: [],
    title: "Sleep until the next round",
    text: "SEBI and IRDAI had nothing new: one line each, then 60 minutes of sleep. A first round on an empty database saves well over 100 PDFs and takes a few minutes; later ones, under a minute.",
    code: "main() · watcher/main.py",
    moves: [["all three done", "s8>s9", 0.05, 0.25, "ok"], ["in 60 minutes", "s9>s1", 0.45, 0.95, "start"]],
    marks: [
      [0.25, { sub: { s9: "sleeping 60 minutes", fail: "retried next round" },
               log: [["log", "INFO SEBI: seen=92 new=0 failed=0"], ["log", "INFO IRDAI: seen=20 new=0 failed=0"], ["log", "INFO sleeping 60 minutes"]] }],
      [0.95, { sub: { s1: "next round in 60 min" } }],
    ],
  },

  // ── When something goes wrong ──
  {
    story: 2, ref: "going wrong", dur: 8400, focus: ["fetch", "sebi", "fail"], tables: ["failures"],
    title: "A regulator's site is down",
    text: "SEBI answers 503 three times, 2 s and then 4 s apart. That regulator is skipped this round, the other two still run, and the next round tries again.",
    code: "get() · watcher/fetch.py · run_source() · watcher/main.py",
    moves: [["GET", "fetch>sebi", 0.03, 0.18, "ext"], ["503", "sebi>fetch", 0.2, 0.34, "bad"], ["try 3", "fetch>sebi", 0.42, 0.56, "ext"],
            ["503", "sebi>fetch", 0.58, 0.72, "bad"], ["listing failed", "fetch>fail", 0.76, 0.95, "bad"]],
    marks: [
      [0.02, { sub: { s1: "round: SEBI" }, rows: { failures: [FAIL.down] } }],
      [0.34, { sub: { fetch: "503: wait 2 s, then 4 s" } }],
      [0.95, { sub: { fetch: IDLE_FETCH, fail: "SEBI: next round" },
               log: ["error", "ERROR SEBI: listing failed: Server error '503 Service Unavailable' for url 'https://www.sebi.gov.in/sebiweb/home/HomeAction.do?…'"] }],
    ],
  },
  {
    story: 2, ref: "going wrong", dur: 8000, focus: ["s4", "rbipage", "fail"], tables: ["failures"],
    title: "A circular's page has no PDF link",
    text: "The page is read, but there's no PDF link on it. That circular isn't saved, and every round tries it again. If it lasts, check the page by hand.",
    code: "resolve_pdf_url() · watcher/sources.py",
    moves: [["GET the page", "s4>fetch", 0.03, 0.2, "svc"], ["GET", "fetch>rbipage", 0.24, 0.4, "ext"], ["HTML, no PDF", "rbipage>fetch", 0.44, 0.6, "bad"],
            ["no PDF link", "s4>fail", 0.66, 0.92, "bad"]],
    marks: [[0.02, { rows: { failures: [FAIL.nolink] } }], [0.92, { sub: { fail: "no PDF link" },
                     log: ["warn", "WARNING RBI failed (https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=…): no PDF link on https://www.rbi.org.in/…"] }]],
  },
  {
    story: 2, ref: "going wrong", dur: 7600, focus: ["s5", "fail"], tables: ["failures"],
    title: "The download is a web page, not a PDF",
    text: "The site answered 200 OK, but with an HTML page. It fails the %PDF check: nothing is kept, and the next round tries again.",
    code: "fetch_new() · watcher/main.py",
    moves: [["<!DOCTYPE html>…", "fetch>s5", 0.05, 0.36, "bad"], ["not a PDF", "s5>fail", 0.46, 0.84, "bad"]],
    marks: [
      [0.02, { rows: { failures: [FAIL.html] } }],
      [0.36, { sub: { s5: "✗ <!DOCTYPE html> …" } }],
      [0.84, { sub: { fail: "not a PDF" },
               log: ["warn", "WARNING IRDAI failed (https://irdai.gov.in/…): not a PDF: https://irdai.gov.in/…"] }],
    ],
  },
  {
    story: 2, ref: "going wrong", dur: 8000, focus: ["s6", "s3obj", "fail"], tables: ["failures"],
    title: "Floci (S3) isn't running",
    text: "The PDF can't be stored, so the watcher stops for this circular before saving anything. Start Floci with its data folder (--persist), and the next round catches up.",
    code: "put_pdf() · watcher/storage.py",
    moves: [["PUT ✗", "s6>s3obj", 0.05, 0.42, "bad"], ["S3 unreachable", "s6>fail", 0.5, 0.88, "bad"]],
    marks: [
      [0.02, { sub: { s5: "✓ it starts with %PDF" }, rows: { failures: [FAIL.floci] } }],
      [0.88, { sub: { fail: "S3 is down" },
               log: ["warn", "WARNING RBI failed (…): Could not connect to the endpoint URL: \"http://host.docker.internal:4566/rci/rbi/…\""] }],
    ],
  },
  {
    story: 2, ref: "going wrong", dur: 9000, focus: ["s7", "s8", "pg", "marks", "fail"], tables: ["failures", "circulars"],
    title: "Redis is down",
    text: "The row was saved, but the task can't be queued. The watcher deletes the row again and counts the circular failed: next round it's unknown, and tried from the download.",
    code: "fetch_new() · watcher/main.py",
    moves: [["INSERT", "s7>pg", 0.02, 0.2, "data"], ["SET ✗", "s8>marks", 0.26, 0.44, "bad"], ["DELETE the row", "s7>pg", 0.5, 0.7, "bad"],
            ["Redis down", "s8>fail", 0.74, 0.94, "bad"]],
    marks: [
      [0.02, { rows: { failures: [FAIL.redis] } }],
      [0.2, { rows: { circulars: [ROW_98, ["99", "RBI", "id=13651", "(the next circular)", "8c41…e7", "rbi/8c41…e7.pdf", "new"]] },
              sub: { pg: "99 · new" }, log: [["sql", "INSERT INTO circulars (…) VALUES ('RBI', 'id=13651', …) → id 99"], ["sql", "COMMIT"]] }],
      [0.44, { log: ["redis", "SET rci:queued:circular_id=99:type=circular.read … → Error 111: Connection refused"] }],
      [0.7, { rows: { circulars: [ROW_98] }, sub: { pg: "99 deleted again" },
              log: [["sql", "DELETE FROM circulars WHERE id = 99"], ["sql", "COMMIT"]] }],
      [0.94, { sub: { fail: "Redis is down" },
               log: ["warn", "WARNING RBI failed (https://www.rbi.org.in/…?Id=13651…): Error 111 connecting to redis:6379. Connection refused."] }],
    ],
  },
  {
    story: 2, ref: "going wrong", dur: 7400, focus: ["s3", "pg", "s1"], tables: ["failures"],
    title: "Postgres is down",
    text: "The watcher can't even ask which ids it knows, so it stops; Docker starts it again and again until Postgres is back, and the next round catches up.",
    code: "run_source() · watcher/main.py",
    moves: [["SELECT ✗", "s3>pg", 0.1, 0.5, "bad"]],
    marks: [[0.02, { rows: { failures: [FAIL.postgres] } }], [0.5, { sub: { s1: "restarting until Postgres is back", fail: "Postgres is down" },
                    log: ["error", "psycopg.OperationalError: connection to server at \"postgres\" failed … (the container exits; Docker starts it again)"] }]],
  },
  {
    story: 2, ref: "going wrong", dur: 8000, focus: ["fail", "s1", "s3"], tables: ["failures"],
    title: "Nothing is skipped for good",
    text: "A circular that failed isn't saved, so it stays unknown to the watcher, and every round tries it again until it works. A circular is saved completely, or not at all.",
    code: "run_source(), fetch_new() · watcher/main.py",
    moves: [["next round", "s9>s1", 0.05, 0.5, "start"], ["id=13651: unknown", "s1>s2", 0.55, 0.75, "start"]],
    marks: [[0.05, { sub: { s1: "next round", s5: "starts with %PDF?", fail: "retried next round" },
                     rows: { failures: [FAIL.down, FAIL.layout, FAIL.nolink, FAIL.html, FAIL.floci, FAIL.redis, FAIL.postgres] } }]],
  },

  // ── What happens next ──
  {
    story: 3, ref: "what's next", dur: 7000, focus: ["lane", "reader"], tables: [],
    title: "The worker takes over",
    text: "The watcher's job ends with the task. The reader reads the PDF with OCR, Gemini sums it up, and each company finds out if it applies. Click the reader to see it all.",
    code: "read_circular() · worker/pipeline.py",
    moves: [["read 98", "lane>reader", 0.2, 0.7, "queue"]],
    marks: [[0.7, { sub: { reader: "reading 98" } }]],
  },
  {
    story: 3, ref: "what's next", dur: 7000, focus: ["s3", "reader"], tables: [],
    title: "Old circulars cost nothing",
    text: "That's why the watcher doesn't filter by date: it records everything it sees. On a first round many are older than 30 days; the reader marks them skipped, with no OCR and no Gemini.",
    code: "read_circular() · worker/pipeline.py",
    moves: [],
  },
  {
    story: 3, ref: "questions", dur: 7600, focus: ["s6", "s3obj", "reader"], tables: ["s3"],
    title: "A correction under a new id",
    text: "To the watcher it's a new circular, saved like any other. If its PDF is byte-for-byte the same file, it gets the same fingerprint, and the reader copies the earlier text instead of reading it again.",
    code: "twin() · worker/pipeline.py",
    moves: [["same bytes, same name", "s6>s3obj", 0.2, 0.7, "data"]],
  },
  {
    story: 3, ref: "questions", dur: 7600, focus: ["s1"], tables: [],
    title: "Check now, and only one watcher",
    text: "docker compose restart watcher starts a round at once. Only one watcher ever runs: two would both download the same new circular, and the database would refuse the second copy.",
    code: "watcher: replicas 1 · docker-compose.yml",
    moves: [["restart: a round now", "s1>s2", 0.3, 0.8, "start"]],
    marks: [[0.2, { sub: { s1: "a round now" }, log: ["app", "docker compose restart watcher"] }]],
  },
];

export default {
  id: "watcher",
  tab: "Watcher",
  hint: "as in the watcher guide",
  heading: "The watcher, in detail",
  lead: "One round of the watcher, as in how_the_watcher_works.md and with its example, RBI circular 98: the nine numbered boxes are the guide's nine steps. Then the three regulators one by one, being polite to their sites, every way a round can go wrong, and what happens next. Under the picture: the rows each step changes, and every request, SQL statement and Redis command.",
  label: "The watcher: the regulators' sites on the left, reached only through fetch.py; the nine numbered steps of one round in the middle; S3, the circulars table, the Redis mark and PDF lane, and the reader on the right.",
  refDoc: "watcher guide",
  size: [1180, 700],
  groups: [[10, 30, 250, 600, "the regulators' websites"], [470, 30, 300, 660, "one round · steps 1–9"],
           [800, 30, 370, 660, "where it saves and queues"]],
  nodes,
  edges,
  tables,
  quietEdges: true,
  stories: ["One round, step by step · RBI circular 98", "The three regulators, one by one",
            "When something goes wrong · all or nothing", "What happens next"],
  steps,
};
