/** The worker in detail: how a loop takes a task from its lane, the reader reading
 * circular 98, a worker checking it for company 1, and every way a task can fail. The
 * names, ids and log lines are the real ones. */
import { geometry, node } from "./player.js";

const IDLE_HEART = "XCLAIM every 60 s";
const NOBODY = "nothing handed out";
const PDF_TASK = "1790…-0 · 0f40…-1";

const nodes = {
  pdflane: node(166, 100, 270, 84, "queue", "PDF lane", "rci:tasks:pdf", { slots: 3, mono: true }),
  mainlane: node(166, 210, 270, 84, "queue", "main lane", "rci:tasks", { slots: 3, mono: true }),
  pending: node(166, 318, 270, 74, "queue", "pending lists", NOBODY, { mono: true }),
  keys: node(166, 420, 270, 62, "queue", "dedupe keys", "rci:queued:…", { mono: true }),
  dead: node(166, 520, 270, 62, "bad", "rci:dead", "tasks given up"),

  pdfloop: node(450, 100, 180, 64, "svc", "PDF loop", "waiting", { idle: "waiting", mono: true }),
  mainloop: node(450, 210, 180, 64, "svc", "main loop", "waiting", { idle: "waiting", mono: true }),
  heart: node(450, 318, 180, 64, "svc", "heartbeat", IDLE_HEART, { idle: IDLE_HEART }),
  fail: node(450, 430, 180, 64, "ask", "failures.py", "wait · retry · give up"),
  finish: node(450, 545, 180, 62, "ok", "finish", "DEL · XADD · XACK"),
  run: node(680, 100, 190, 64, "svc", "run_task()", "TASKS[type](…)", { mono: true }),
  fnread: node(680, 225, 190, 64, "svc", "read_circular()", "pipeline.py", { mono: true }),
  fnassess: node(680, 340, 190, 64, "svc", "assess() · match()", "pipeline.py", { mono: true }),

  s3: node(994, 80, 330, 34, "data", "S3", "the PDFs", { inline: true }),
  ocr: node(994, 122, 330, 34, "gpu", "OCR · GPU", "a page at a time", { inline: true }),
  chat: node(994, 164, 330, 34, "ext", "Gemini chat", "JSON replies", { inline: true }),
  emb: node(994, 206, 330, 34, "ext", "Gemini embeddings", "768 numbers", { inline: true }),
  circulars: node(994, 296, 330, 34, "data", "circulars", "98 · new", { inline: true }),
  ocrpages: node(994, 340, 330, 34, "data", "ocr_pages", "empty", { inline: true }),
  assessments: node(994, 384, 330, 34, "data", "assessments", "—", { inline: true }),
  policies: node(994, 428, 330, 34, "data", "policies · controls", "company 1: 4 for RBI", { inline: true }),
  checks: node(994, 472, 330, 34, "data", "policy_checks", "—", { inline: true }),
  gaps: node(994, 516, 330, 34, "gap", "gaps · gap_events", "—", { inline: true }),
};

const { at, line, curve } = geometry(nodes);
/** From a pipeline function to a service or a table on the right. */
const right = (from, to, d = 0) =>
  curve(at(from, "r", d), [803, nodes[from].y + d], [806, nodes[to].y], at(to, "l"));

const edges = {
  "pdflane>pdfloop": line(at("pdflane", "r"), at("pdfloop", "l")),
  "mainlane>mainloop": line(at("mainlane", "r"), at("mainloop", "l")),
  "pdfloop>pending": curve(at("pdfloop", "l", 22), [332, 122], [332, 300], at("pending", "r", -18)),
  "mainloop>pending": curve(at("mainloop", "l", 22), [338, 232], [338, 318], at("pending", "r")),
  "heart>pending": line(at("heart", "l"), at("pending", "r", 18)),
  "pdfloop>run": line(at("pdfloop", "r"), at("run", "l")),
  "mainloop>run": curve(at("mainloop", "r"), [562, 210], [562, 116], at("run", "l", 16)),
  "run>fnread": line(at("run", "b"), at("fnread", "t")),
  "run>fnassess": curve(at("run", "b", -70), [568, 190], [568, 340], at("fnassess", "l")),
  "run>fail": curve(at("run", "b", -80), [562, 200], [562, 430], at("fail", "r")),
  "run>finish": curve(at("run", "b", -85), [556, 210], [556, 545], at("finish", "r")),
  "fnread>run": curve(at("fnread", "r", -14), [800, 211], [800, 110], at("run", "r", 10)),
  "finish>keys": curve(at("finish", "l", -10), [328, 535], [328, 420], at("keys", "r")),
  "finish>mainlane": curve(at("finish", "l", -20), [322, 525], [322, 225], at("mainlane", "r", 15)),
  "finish>pending": curve(at("finish", "l"), [334, 545], [334, 330], at("pending", "r", 12)),
  "fail>pending": curve(at("fail", "l", -12), [338, 418], [338, 340], at("pending", "r", 24)),
  "fail>dead": curve(at("fail", "l", 12), [330, 442], [330, 520], at("dead", "r")),
  "fnread>s3": right("fnread", "s3", -24),
  "fnread>ocr": right("fnread", "ocr", -16),
  "fnread>chat": right("fnread", "chat", -8),
  "fnread>emb": right("fnread", "emb"),
  "fnread>circulars": right("fnread", "circulars", 8),
  "fnread>ocrpages": right("fnread", "ocrpages", 16),
  "fnread>assessments": right("fnread", "assessments", 24),
  "fnassess>chat": right("fnassess", "chat", -24),
  "fnassess>circulars": right("fnassess", "circulars", -16),
  "fnassess>assessments": right("fnassess", "assessments", -8),
  "fnassess>policies": right("fnassess", "policies"),
  "fnassess>checks": right("fnassess", "checks", 12),
  "fnassess>gaps": right("fnassess", "gaps", 24),
};

const SHA = "93c94462…b380d5";

const steps = [
  // ── Story 1: taking a task ──
  {
    story: 0, dur: 5600, focus: ["pdfloop", "mainloop"],
    title: "Two loops, one per lane",
    text: "The program starts a loop for each lane in LANES, each in its own thread. In Docker the reader runs only the PDF loop, and each worker only the main loop.",
    code: "main(), lanes(), serve() · worker/main.py",
    moves: [],
    marks: [[0.3, { log: [["log", "INFO worker 0f4037061e71-1: lanes pdf, using gemini-3.5-flash-lite, waiting for tasks"],
                          ["log", "INFO worker 6a6d2c41ab44-1: lanes main, using gemini-3.5-flash-lite, waiting for tasks"]] }]],
  },
  {
    story: 0, dur: 5200, focus: ["pdfloop", "pending"],
    title: "First: my own unfinished task",
    text: "Each turn starts with XREADGROUP … 0: a task this loop was handed before but never finished, after a retry or a restart. None here.",
    code: "next_task() · worker/main.py",
    moves: [["XREADGROUP 0", "pdfloop>pending", 0.05, 0.42, "queue"], ["none", "pending>pdfloop", 0.52, 0.88, "queue"]],
    marks: [[0.42, { log: ["redis", "XREADGROUP GROUP workers 0f4037061e71-1 COUNT 1 STREAMS rci:tasks:pdf 0 → (nothing)"] }]],
  },
  {
    story: 0, dur: 5400, focus: ["pdfloop", "pending"],
    title: "Then: an abandoned task",
    text: "Then XAUTOCLAIM: a task on another worker's pending list, untouched for 5 minutes (CLAIM_IDLE_SECONDS), belongs to a dead worker. None here.",
    code: "next_task() · worker/main.py",
    moves: [["XAUTOCLAIM", "pdfloop>pending", 0.05, 0.42, "queue"], ["none", "pending>pdfloop", 0.52, 0.88, "queue"]],
    marks: [[0.42, { log: ["redis", "XAUTOCLAIM rci:tasks:pdf workers 0f4037061e71-1 300000 0-0 COUNT 1 → (nothing)"] }]],
  },
  {
    story: 0, dur: 5800, focus: ["pdflane", "pdfloop", "pending"],
    title: "Then: a new task",
    text: "Then XREADGROUP … >, waiting up to 5 s for a task nobody has had. read 98 arrives, and Redis writes this loop's name next to it on the pending list.",
    code: "next_task() · worker/main.py",
    moves: [["read 98", "pdflane>pdfloop", 0.15, 0.6, "queue"]],
    marks: [
      [0.15, { slots: { pdflane: [] } }],
      [0.6, { sub: { pdfloop: "read 98", pending: `${PDF_TASK} · idle 0 s` },
              log: ["redis", "XREADGROUP GROUP workers 0f4037061e71-1 COUNT 1 BLOCK 5000 STREAMS rci:tasks:pdf > → 1790831159691-0 {type: circular.read, circular_id: 98}"] }],
    ],
  },
  {
    story: 0, dur: 6200, focus: ["heart", "pending"],
    title: "Keep it while working",
    text: "While the task runs, a heartbeat thread sends XCLAIM every 60 s. That puts its idle time back to 0, so a slow PDF is never taken over by another worker.",
    code: "keep_claimed(), HEARTBEAT_SECONDS · worker/main.py",
    moves: [["XCLAIM", "heart>pending", 0.42, 0.72, "queue"]],
    marks: [
      [0.15, { sub: { pending: `${PDF_TASK} · idle 59 s` } }],
      [0.4, { sub: { heart: "XCLAIM: still mine" } }],
      [0.72, { sub: { pending: `${PDF_TASK} · idle 0 s`, heart: IDLE_HEART },
               log: ["redis", "XCLAIM rci:tasks:pdf workers 0f4037061e71-1 0 1790831159691-0 JUSTID"] }],
    ],
  },
  {
    story: 0, dur: 5200, focus: ["pdfloop", "run", "fnread"],
    title: "Call the task's function",
    text: "run_task() opens a database session and calls TASKS[type] with the task's ids: circular.read becomes read_circular(session, circular_id=98).",
    code: "run_task(), TASKS · worker/main.py",
    moves: [["circular.read 98", "pdfloop>run", 0.05, 0.45, "svc"], ["circular_id=98", "run>fnread", 0.55, 0.9, "svc"]],
    marks: [[0.45, { sub: { run: "read_circular(98)" } }]],
  },

  // ── Story 2: the reader reads circular 98 ──
  {
    story: 1, dur: 5600, focus: ["fnread", "circulars"],
    title: "New and recent?",
    text: "read_circular() loads circular 98. One older than LOOKBACK_DAYS (30) would be marked skipped, and a failed one left alone. 98 is new and recent.",
    code: "read_circular(), cutoff() · worker/pipeline.py",
    moves: [["load 98", "fnread>circulars", 0.05, 0.4, "data"], ["new · 24 Sep", "circulars>fnread", 0.5, 0.88, "data"]],
    marks: [[0.4, { log: ["sql", "SELECT * FROM circulars WHERE id = 98 → status 'new', published 2026-09-24"] }]],
  },
  {
    story: 1, dur: 5600, focus: ["fnread", "circulars"],
    title: "A twin with its text?",
    text: "If another circular has the same sha256 and its text already, the text is copied and OCR is skipped. Circular 98 has no twin.",
    code: "twin() · worker/pipeline.py",
    moves: [["same sha256?", "fnread>circulars", 0.05, 0.4, "data"], ["none", "circulars>fnread", 0.5, 0.88, "data"]],
    marks: [[0.4, { log: ["sql", `SELECT * FROM circulars WHERE sha256 = '${SHA}' AND id <> 98 AND text IS NOT NULL → (none)`] }]],
  },
  {
    story: 1, dur: 6400, focus: ["fnread", "ocrpages", "s3"],
    title: "Pages read before? Then the PDF",
    text: "ocr_pages holds the pages an earlier try already read: none yet. Then the PDF comes from S3, straight into memory.",
    code: "ocr_text() · worker/pipeline.py · get_pdf() · worker/storage.py",
    moves: [
      ["saved pages?", "fnread>ocrpages", 0.03, 0.22, "data"], ["none", "ocrpages>fnread", 0.26, 0.44, "data"],
      ["GET", "fnread>s3", 0.5, 0.68, "data"], ["PDF", "s3>fnread", 0.72, 0.92, "data"],
    ],
    marks: [
      [0.22, { log: ["sql", `SELECT page, text FROM ocr_pages WHERE sha256 = '${SHA}' → (none)`] }],
      [0.68, { log: ["s3", "GET s3://rci/rbi/93c944624b4c6ec1589c782c37c4dce064f4a5a16bffaf52f08cb00661b380d5.pdf"] }],
    ],
  },
  {
    story: 1, dur: 8400, focus: ["fnread", "ocr", "ocrpages"],
    title: "OCR, a page at a time",
    text: "Each page is rendered at 200 DPI and sent to OCR on the GPU; a blank page is never sent. Each page's text is saved the moment it comes back.",
    code: "pages(), ocr_page(), remove_det() · worker/ocr.py",
    moves: [
      ["page 1", "fnread>ocr", 0.02, 0.14, "gpu"], ["text", "ocr>fnread", 0.17, 0.29, "gpu"],
      ["save page 1", "fnread>ocrpages", 0.31, 0.42, "data"],
      ["page 2", "fnread>ocr", 0.45, 0.57, "gpu"], ["text", "ocr>fnread", 0.6, 0.72, "gpu"],
      ["save page 2", "fnread>ocrpages", 0.74, 0.85, "data"],
    ],
    marks: [
      [0.14, { log: ["ocr", "POST http://ocr:8000/v1/chat/completions  page 1, 200 DPI PNG, \"<image>document parsing.\""] }],
      [0.42, { sub: { ocrpages: `${SHA} · 1 page` }, log: [["sql", `INSERT INTO ocr_pages (sha256, page, text) VALUES ('${SHA}', 0, '…')`], ["sql", "COMMIT"]] }],
      [0.57, { log: ["ocr", "POST http://ocr:8000/v1/chat/completions  page 2, 200 DPI PNG"] }],
      [0.85, { sub: { ocrpages: `${SHA} · 2 pages` }, log: [["sql", `INSERT INTO ocr_pages (sha256, page, text) VALUES ('${SHA}', 1, '…')`], ["sql", "COMMIT"]] }],
      [0.92, { log: ["app", "page 3: no text, images or drawings → blank, not sent"] }],
    ],
  },
  {
    story: 1, dur: 6000, focus: ["fnread", "circulars", "ocrpages"],
    title: "Save the whole text",
    text: "The pages are joined into circular 98's text, 2,431 characters, with status parsed. Its ocr_pages rows are deleted in the same commit.",
    code: "read_circular(), ocr_text() · worker/pipeline.py",
    moves: [["text", "fnread>circulars", 0.05, 0.45, "data"], ["DELETE", "fnread>ocrpages", 0.3, 0.65, "data"]],
    marks: [[0.65, {
      sub: { circulars: "98 · parsed · 2,431 chars", ocrpages: "empty" },
      log: [["sql", "UPDATE circulars SET text = '…', status = 'parsed' WHERE id = 98"],
            ["sql", `DELETE FROM ocr_pages WHERE sha256 = '${SHA}'`], ["sql", "COMMIT"],
            ["log", "INFO #98 parsed: 2431 chars"]],
    }]],
  },
  {
    story: 1, dur: 6400, focus: ["fnread", "chat", "circulars"],
    title: "Gemini sums it up",
    text: "Gemini gets the text (up to 100,000 characters) and replies in a fixed JSON shape: who it's addressed to, a short summary, and every obligation.",
    code: "summarize(), CircularSummary · worker/llm.py",
    moves: [["the text", "fnread>chat", 0.03, 0.35, "ext"], ["JSON", "chat>fnread", 0.42, 0.72, "ext"],
            ["summary", "fnread>circulars", 0.76, 0.95, "data"]],
    marks: [
      [0.72, { log: ["llm", "summarize(98) → {addressed_to: 'The Chairpersons/ CEOs of the Commercial Banks, …', summary: '…', requirements: [4 items]}"] }],
      [0.95, { sub: { circulars: "98 · summary · 4 obligations" },
               log: [["sql", "UPDATE circulars SET addressed_to = …, summary = …, requirements = … WHERE id = 98"], ["sql", "COMMIT"],
                     ["log", "INFO #98 read: addressed to 'The Chairpersons/ CEOs of the Commercial Banks, Small Finance Banks, Payment Ban'"]] }],
    ],
  },
  {
    story: 1, dur: 6000, focus: ["fnread", "emb", "circulars"],
    title: "Turn it into numbers",
    text: "The title, summary and obligations go to gemini-embedding-001 and come back as 768 numbers. Saved, and circular 98 is now read.",
    code: "embed_circular() · worker/pipeline.py · embed() · worker/llm.py",
    moves: [["title + summary", "fnread>emb", 0.03, 0.35, "ext"], ["768 numbers", "emb>fnread", 0.42, 0.72, "ext"],
            ["embedding", "fnread>circulars", 0.76, 0.95, "data"]],
    marks: [
      [0.72, { log: ["llm", "embed([title + summary + 4 obligations], RETRIEVAL_QUERY) → 768 numbers"] }],
      [0.95, { sub: { circulars: "98 · read" },
               log: [["sql", "UPDATE circulars SET embedding = [0.021, -0.013, …], embedding_model = 'gemini-embedding-001', status = 'read' WHERE id = 98"],
                     ["sql", "COMMIT"]] }],
    ],
  },
  {
    story: 1, dur: 5800, focus: ["fnread", "assessments", "run"],
    title: "A to-do per company",
    text: "Each company gets an assessments row, pending. The function returns one circular.assess per company: the tasks to queue next.",
    code: "add_assessments(), pending() · worker/pipeline.py",
    moves: [["2 rows", "fnread>assessments", 0.05, 0.45, "data"], ["2 follow-ups", "fnread>run", 0.55, 0.92, "svc"]],
    marks: [[0.45, { sub: { assessments: "98: company 1, 2 pending" },
                     log: [["sql", "INSERT INTO assessments (company_id, circular_id, status) VALUES (1, 98, 'pending'), (2, 98, 'pending') ON CONFLICT DO NOTHING"],
                           ["sql", "COMMIT"]] }]],
  },
  {
    story: 1, dur: 7000, focus: ["run", "finish", "keys", "mainlane", "pending"],
    title: "Finish, in this order",
    text: "Delete the task's dedupe key, XADD the follow-ups to the main lane, then XACK. If the reader dies before the XACK, the task just runs once more.",
    code: "run_task() · worker/main.py · enqueue() · common/queue.py",
    moves: [
      ["follow-ups", "run>finish", 0.02, 0.24, "ok"], ["DEL key", "finish>keys", 0.26, 0.44, "queue"],
      ["XADD ×2", "finish>mainlane", 0.46, 0.68, "queue"], ["XACK", "finish>pending", 0.72, 0.93, "ok"],
    ],
    marks: [
      [0.44, { log: ["redis", "DEL rci:queued:circular_id=98:type=circular.read"] }],
      [0.68, { slots: { mainlane: ["98 · 1", "98 · 2"] }, sub: { keys: "circular.assess 98 · ×2" },
               log: [["redis", "SET rci:queued:circular_id=98:company_id=1:type=circular.assess 1 NX EX 86400 → OK"],
                     ["redis", "XADD rci:tasks * type circular.assess company_id 1 circular_id 98"],
                     ["redis", "XADD rci:tasks * type circular.assess company_id 2 circular_id 98  (and its key)"]] }],
      [0.93, { sub: { pending: NOBODY, pdfloop: "waiting", run: "TASKS[type](…)" },
               log: ["redis", "XACK rci:tasks:pdf workers 1790831159691-0"] }],
    ],
  },

  // ── Story 3: a worker checks it for company 1 ──
  {
    story: 2, dur: 6000, focus: ["mainlane", "mainloop", "run", "fnassess"],
    title: "Take the next note",
    text: "The main loop's XREADGROUP returns check 98 for company 1, while another worker takes company 2's. run_task() calls assess(1, 98).",
    code: "next_task(), run_task() · worker/main.py",
    moves: [["98 · 1", "mainlane>mainloop", 0.04, 0.36, "queue"], ["circular.assess", "mainloop>run", 0.42, 0.66, "svc"],
            ["assess(1, 98)", "run>fnassess", 0.7, 0.95, "svc"]],
    marks: [
      [0.04, { slots: { mainlane: ["98 · 2"] } }],
      [0.36, { sub: { mainloop: "98 · company 1", pending: "…-0 · 6a6d…-1 · idle 0 s" },
               log: ["redis", "XREADGROUP GROUP workers 6a6d2c41ab44-1 COUNT 1 BLOCK 5000 STREAMS rci:tasks > → {type: circular.assess, company_id: 1, circular_id: 98}"] }],
      [0.5, { slots: { mainlane: [] } }],
      [0.66, { sub: { run: "assess(1, 98)" } }],
    ],
  },
  {
    story: 2, dur: 6400, focus: ["fnassess", "chat", "assessments"],
    title: "Does it apply?",
    text: "Gemini reads company 1's description and the first 4,000 characters of circular 98, and answers: it applies, with a one-line reason.",
    code: "assess() · worker/pipeline.py · check_applicability() · worker/llm.py",
    moves: [["applies?", "fnassess>chat", 0.03, 0.35, "ext"], ["yes + why", "chat>fnassess", 0.42, 0.72, "ok"],
            ["applicable", "fnassess>assessments", 0.76, 0.95, "data"]],
    marks: [
      [0.72, { log: ["llm", "check_applicability(company 1, 98) → {applies_to_company: true, reason: 'Addressed to NBFCs, and the company is an NBFC.'}"] }],
      [0.95, { sub: { assessments: "98 · 1: applies" },
               log: [["sql", "UPDATE assessments SET applicable = true, applies_reason = '…' WHERE company_id = 1 AND circular_id = 98"], ["sql", "COMMIT"]] }],
    ],
  },
  {
    story: 2, dur: 6600, focus: ["fnassess", "policies"],
    title: "Score the policies",
    text: "Company 1's RBI policies are scored against the circular: each policy's best 5,000-character chunk, by cosine similarity. No Gemini call.",
    code: "match(), cosine(), embed_policy() · worker/pipeline.py",
    moves: [["RBI policies?", "fnassess>policies", 0.03, 0.32, "data"], ["4 + embeddings", "policies>fnassess", 0.4, 0.72, "data"]],
    marks: [
      [0.32, { log: ["sql", "SELECT * FROM policies WHERE company_id = 1 → 4 tagged RBI, all embedded with gemini-embedding-001"] }],
      [0.8, { sub: { fnassess: "KYC .82 DRP .58 DLP .55" },
              log: ["app", "cosine: POL-KYC 0.82 · POL-DRP 0.58 · POL-DLP 0.55 · POL-IT 0.31 → the 3 closest (MATCH_TOP_K)"] }],
    ],
  },
  {
    story: 2, dur: 5600, focus: ["fnassess", "checks", "gaps"],
    title: "Never ask twice",
    text: "A policy already judged for 98 at its current version, or with a gap from 98, is skipped: the same question is never paid for twice.",
    code: "match() · worker/pipeline.py",
    moves: [["judged?", "fnassess>checks", 0.03, 0.25, "data"], ["none", "checks>fnassess", 0.28, 0.48, "data"],
            ["a gap?", "fnassess>gaps", 0.52, 0.72, "data"], ["none", "gaps>fnassess", 0.75, 0.95, "data"]],
    marks: [
      [0.25, { log: ["sql", "SELECT policy_id, policy_version FROM policy_checks WHERE circular_id = 98 → (none)"] }],
      [0.72, { log: ["sql", "SELECT policy_id FROM gaps WHERE circular_id = 98 → (none)"] }],
    ],
  },
  {
    story: 2, dur: 6800, focus: ["fnassess", "chat", "policies"],
    title: "Is POL-KYC out of date?",
    text: "Gemini gets the company, the circular's obligations, POL-KYC's text and its controls, and replies: what's missing, how severe, which controls, a draft fix.",
    code: "judge_policy() · worker/pipeline.py · assess(), Verdict · worker/llm.py",
    moves: [["controls", "policies>fnassess", 0.02, 0.2, "data"], ["POL-KYC v1?", "fnassess>chat", 0.24, 0.5, "ext"],
            ["out of date", "chat>fnassess", 0.56, 0.85, "gap"]],
    marks: [
      [0.2, { log: ["sql", "SELECT * FROM controls WHERE policy_id = 9"] }],
      [0.85, { sub: { fnassess: "KYC: out of date · high" },
               log: ["llm", "assess(98, POL-KYC v1) → {impacted: true, severity: 'high', missing_from_policy: '…', affected_controls: […], draft_change: '…'}"] }],
    ],
  },
  {
    story: 2, dur: 7000, focus: ["fnassess", "checks", "gaps"],
    title: "Verdict and gap, one commit",
    text: "The verdict goes in policy_checks. Out of date, so a gap for the policy's owner too, due in 7 days (high), with its first gap_events line. One commit.",
    code: "judge_policy(), DUE_DAYS · worker/pipeline.py",
    moves: [["verdict", "fnassess>checks", 0.05, 0.4, "data"], ["gap + event", "fnassess>gaps", 0.3, 0.68, "gap"]],
    marks: [[0.68, {
      sub: { checks: "98 × POL-KYC v1 · impacted", gaps: "POL-KYC · high · 7 days" },
      log: [["sql", "INSERT INTO policy_checks (circular_id, policy_id, policy_version, similarity, impacted) VALUES (98, 9, 1, 0.82, true)"],
            ["sql", "INSERT INTO gaps (company_id, circular_id, policy_id, severity, owner, due_date, draft_change, …) VALUES (1, 98, 9, 'high', 'head.kyc@…', today + 7, '…')"],
            ["sql", "INSERT INTO gap_events (gap_id, actor, action, note) VALUES (…, 'agent', 'opened', '…')"],
            ["sql", "COMMIT"], ["log", "INFO #98 vs POL-KYC v1 (0.82): GAP"]],
    }]],
  },
  {
    story: 2, dur: 7200, focus: ["fnassess", "chat", "assessments", "finish"],
    title: "The other two, then done",
    text: "POL-DRP and POL-DLP come back up to date: a verdict each, no gap. The assessment is marked done, and the task finishes: DEL, then XACK.",
    code: "assess() · worker/pipeline.py · run_task() · worker/main.py",
    moves: [["POL-DRP, POL-DLP?", "fnassess>chat", 0.02, 0.22, "ext"], ["up to date ×2", "chat>fnassess", 0.25, 0.45, "ok"],
            ["done", "fnassess>assessments", 0.48, 0.64, "data"], ["finish", "run>finish", 0.66, 0.8, "ok"],
            ["XACK", "finish>pending", 0.82, 0.96, "ok"]],
    marks: [
      [0.45, { sub: { checks: "98 · 3 verdicts, 1 impacted" },
               log: [["log", "INFO #98 vs POL-DRP v1 (0.58): up to date"], ["log", "INFO #98 vs POL-DLP v1 (0.55): up to date"]] }],
      [0.64, { sub: { assessments: "98 · 1: done, 1 gap" },
               log: [["sql", "UPDATE assessments SET status = 'done' WHERE company_id = 1 AND circular_id = 98"], ["sql", "COMMIT"],
                     ["log", "INFO #98 for company 1: applies: True, gaps opened: ['POL-KYC']"]] }],
      [0.96, { sub: { pending: NOBODY, mainloop: "waiting", run: "TASKS[type](…)", fnassess: "pipeline.py" },
               log: [["redis", "DEL rci:queued:circular_id=98:company_id=1:type=circular.assess"],
                     ["redis", "XACK rci:tasks workers …-0"]] }],
    ],
  },

  // ── Story 4: when something fails ──
  {
    story: 3, dur: 7000, focus: ["fnread", "ocr", "fail", "pending"],
    title: "A service is down: wait",
    text: "OCR still loading, or Gemini answering 429: the step is rolled back, the loop waits 60 s and runs the same task again, as long as it takes.",
    code: "should_wait() · worker/failures.py · run_task() · worker/main.py",
    moves: [["page 1", "fnread>ocr", 0.03, 0.2, "gpu"], ["refused", "ocr>fnread", 0.22, 0.36, "bad"],
            ["ConnectError", "run>fail", 0.4, 0.6, "bad"], ["stays pending", "fail>pending", 0.64, 0.88, "queue"]],
    marks: [
      [0.01, { sub: { pdfloop: "read 98", run: "read_circular(98)", pending: `${PDF_TASK} · idle 0 s`, circulars: "98 · new" } }],
      [0.6, { sub: { fail: "wait 60 s, then again" }, log: ["warn", "WARNING OCR or Gemini unavailable ([Errno 111] Connection refused); retrying"] }],
      [0.88, { sub: { pdfloop: "read 98 · in 60 s" } }],
    ],
  },
  {
    story: 3, dur: 6600, focus: ["fnread", "chat", "fail"],
    title: "A hiccup: retry",
    text: "A timeout, a 5xx, or a reply not in the JSON shape: the task is tried again at once, up to 3 tries. Everything saved before the hiccup is kept.",
    code: "should_retry(), MAX_TRIES · worker/failures.py",
    moves: [["the text", "fnread>chat", 0.03, 0.22, "ext"], ["not JSON", "chat>fnread", 0.25, 0.42, "bad"],
            ["BadReply", "run>fail", 0.46, 0.64, "bad"], ["try 2 of 3", "fail>pending", 0.68, 0.9, "queue"]],
    marks: [[0.64, { sub: { fail: "retry: try 2 of 3", pdfloop: "read 98 · try 2" },
                     log: ["warn", "WARNING {'type': 'circular.read', 'circular_id': '98'} failed (BadReply: not the asked-for JSON); trying again"] }]],
  },
  {
    story: 3, dur: 7400, focus: ["fail", "dead", "pending", "circulars"],
    title: "Anything else: give up",
    text: "No text in the PDF, or Floci down: the circular is marked failed with the error, the task is copied to rci:dead, its key deleted, then XACK.",
    code: "give_up() · worker/main.py",
    moves: [["ValueError", "run>fail", 0.03, 0.24, "bad"], ["copy", "fail>dead", 0.34, 0.6, "bad"], ["XACK", "fail>pending", 0.68, 0.92, "ok"]],
    marks: [
      [0.24, { sub: { fail: "give up: no text in the PDF", circulars: "98 · failed" },
               log: [["error", "ERROR {'type': 'circular.read', 'circular_id': '98'} failed for good"],
                     ["sql", "UPDATE circulars SET status = 'failed', error = 'ValueError: OCR found no text in the PDF' WHERE id = 98"], ["sql", "COMMIT"]] }],
      [0.6, { sub: { dead: "circular.read 98 · ValueError" },
              log: ["redis", "XADD rci:dead * type circular.read circular_id 98 stream rci:tasks:pdf task_id 1790831159691-0 error 'ValueError: OCR found no text in the PDF'"] }],
      [0.92, { sub: { pending: NOBODY, pdfloop: "waiting", run: "TASKS[type](…)" },
               log: [["redis", "DEL rci:queued:circular_id=98:type=circular.read"], ["redis", "XACK rci:tasks:pdf workers 1790831159691-0"]] }],
    ],
  },
  {
    story: 3, dur: 8000, focus: ["pdfloop", "pending", "ocrpages"],
    title: "The reader dies mid-PDF",
    text: "A killed reader never sends XACK, so its task stays pending. Restarted, it finds the task at once; a new container takes it over after 5 minutes.",
    code: "next_task() · worker/main.py · ocr_text() · worker/pipeline.py",
    moves: [["XAUTOCLAIM", "pdfloop>pending", 0.42, 0.6, "queue"], ["1790…-0", "pending>pdfloop", 0.62, 0.8, "queue"],
            ["read 98", "pdfloop>run", 0.84, 0.97, "svc"]],
    marks: [
      [0.01, { sub: { pdfloop: "✗ killed on page 3", pending: `${PDF_TASK} · idle 0 s`, circulars: "98 · new",
                      ocrpages: `${SHA} · 2 pages`, fail: "wait · retry · give up", dead: "tasks given up" } }],
      [0.2, { sub: { pending: `${PDF_TASK} · idle 300 s` } }],
      [0.36, { sub: { pdfloop: "new container: c9f5…-1" } }],
      [0.8, { sub: { pending: "1790…-0 · c9f5…-1 · idle 0 s", pdfloop: "read 98, from page 3" },
              log: [["redis", "XAUTOCLAIM rci:tasks:pdf workers c9f550b306ee-1 300000 0-0 COUNT 1 → 1790831159691-0"],
                    ["log", "INFO #98: 2 pages OCR'd before, carrying on"]] }],
    ],
  },
];

export default {
  id: "worker",
  tab: "Worker",
  hint: "the reader and the workers",
  heading: "The worker, in detail",
  lead: "The program behind the reader and the workers: how a loop takes a task from its Redis lane, the reader turning circular 98 into text, a summary and numbers, a worker checking it for company 1 and opening a gap, and what happens when something fails. Every Redis command and SQL statement is in the log underneath.",
  label: "The worker program: a loop per Redis lane takes tasks and runs them through run_task; read_circular uses S3, OCR and Gemini and writes circulars, ocr_pages and assessments; assess uses Gemini and writes assessments, policy_checks and gaps; finishing deletes the dedupe key, queues follow-ups and acknowledges the task; failures wait, retry or give up to rci:dead.",
  size: [1180, 620],
  groups: [[16, 30, 300, 580, "Redis"], [340, 30, 456, 580, "the worker program"],
           [814, 30, 350, 204, "services it calls"], [814, 246, 350, 300, "Postgres tables"]],
  nodes,
  edges,
  quietEdges: true,
  start: { slots: { pdflane: ["read 98"] }, sub: { keys: "circular_id=98:type=circular.read" } },
  stories: ["Story 1 · Taking a task", "Story 2 · The reader reads circular 98", "Story 3 · A worker checks it for company 1",
            "Story 4 · When something fails"],
  steps,
};
