/** The worker in detail, step by step as in backend/worker/INTERNALS.md: the same 18
 * steps in the same groups, with its example (circular 98, a 3-page PDF whose last page is
 * blank; company 1, an NBFC with four RBI policies; company 2, a stock broker), its tables
 * after each step, and the log lines, Redis commands and SQL underneath. */
import { geometry, node } from "./player.js";

const W = "waiting";
const NOBODY = "nothing handed out";
const READER = "e02ff2af94f5-1";
const W1 = "4b2f9c0d1e7a-1";
const W2 = "a71c3e5f0b92-1";
const SHA = "3f9a…c1";

const nodes = {
  // who queues (INTERNALS step 16), and Redis
  watcher: node(66, 90, 100, 52, "svc", "watcher", "circular.read"),
  api: node(170, 90, 100, 52, "svc", "api", "other tasks"),
  pdf: node(118, 232, 206, 84, "queue", "PDF lane", "rci:tasks:pdf", { slots: 2, mono: true }),
  main: node(118, 337, 206, 84, "queue", "main lane", "rci:tasks", { slots: 3, mono: true }),
  pending: node(118, 442, 206, 64, "queue", "pending lists", NOBODY, { mono: true }),
  marks: node(118, 530, 206, 56, "queue", "marks", "none", { mono: true }),
  dead: node(118, 612, 206, 56, "bad", "rci:dead", "nothing given up"),
  // the program, three copies (steps 1 to 3)
  reader: node(335, 232, 168, 70, "svc", "reader", W, { idle: W, mono: true }),
  w1: node(335, 337, 168, 70, "svc", "worker 1", W, { idle: W, mono: true }),
  w2: node(335, 432, 168, 70, "svc", "worker 2", W, { idle: W, mono: true }),
  // the numbered steps
  s4: node(545, 95, 196, 52, "ask", "skip or read?", "status · date", { num: 4 }),
  s5: node(545, 175, 196, 52, "gpu", "PDF → text", "OCR, page by page", { num: 5 }),
  s6: node(545, 255, 196, 52, "ext", "summarise it", "Gemini: 3 questions", { num: 6 }),
  s7: node(545, 335, 196, 52, "ext", "into numbers", "an embedding", { num: 7 }),
  s8: node(545, 415, 196, 52, "data", "a to-do each", "per company", { num: 8 }),
  s9: node(545, 495, 196, 52, "queue", "finish the task", "DEL · XADD · XACK", { num: 9 }),
  s10: node(767, 95, 196, 52, "ask", "does it apply?", "per company", { num: 10 }),
  s11: node(767, 175, 196, 52, "data", "closest policies", "top 3, no Gemini", { num: 11 }),
  s12: node(767, 255, 196, 52, "ext", "out of date?", "a verdict, a gap", { num: 12 }),
  s13: node(767, 335, 196, 52, "ok", "mark it done", "assessment done", { num: 13 }),
  s14: node(767, 415, 196, 52, "svc", "a policy saved", "policy.check", { num: 14 }),
  s15: node(767, 495, 196, 52, "svc", "a new description", "company.refresh", { num: 15 }),
  s17: node(545, 610, 196, 52, "bad", "something fails", "wait · retry · give up", { num: 17 }),
  s18: node(767, 610, 196, 52, "bad", "a worker dies", "another takes over", { num: 18 }),
  // what it calls, and the tables
  s3: node(1024, 80, 276, 34, "data", "S3", "the PDFs", { inline: true }),
  ocr: node(1024, 120, 276, 34, "gpu", "OCR · GPU", "a page at a time", { inline: true }),
  chat: node(1024, 160, 276, 34, "ext", "Gemini chat", "JSON answers", { inline: true }),
  emb: node(1024, 200, 276, 34, "ext", "Gemini embeddings", "768 numbers", { inline: true }),
  companies: node(1024, 284, 276, 34, "data", "companies", "1 NBFC · 2 broker", { inline: true }),
  circulars: node(1024, 324, 276, 34, "data", "circulars", "98 · new", { inline: true }),
  ocrpages: node(1024, 364, 276, 34, "data", "ocr_pages", "empty", { inline: true }),
  assessments: node(1024, 404, 276, 34, "data", "assessments", "—", { inline: true }),
  policies: node(1024, 444, 276, 34, "data", "policies · controls", "1: four for RBI", { inline: true }),
  checks: node(1024, 484, 276, 34, "data", "policy_checks", "—", { inline: true }),
  gaps: node(1024, 524, 276, 34, "gap", "gaps · gap_events", "—", { inline: true }),
};

const { at, line, curve, via } = geometry(nodes);
const ROW = { s4: 95, s5: 175, s6: 255, s7: 335, s8: 415, s9: 495, s17: 610,
              s10: 95, s11: 175, s12: 255, s13: 335, s14: 415, s15: 495 };
/** A step box to a service or table on the right, along the corridor under its row. */
const out = (from, to, d = 0) => via(at(from, "r", d), ROW[from] === 610 ? 650 : ROW[from] + 40, at(to, "l"));

const edges = {
  "watcher>pdf": line(at("watcher", "b"), at("pdf", "t", -52)),
  "api>pdf": line(at("api", "b"), at("pdf", "t", 52)),
  "api>main": curve(at("api", "r"), [234, 90], [234, 337], at("main", "r")),
  "pdf>reader": line(at("pdf", "r"), at("reader", "l")),
  "main>w1": line(at("main", "r", -8), at("w1", "l", -8)),
  "main>w2": curve(at("main", "r", 14), [236, 351], [236, 432], at("w2", "l")),
  "reader>main": curve(at("reader", "l", 14), [236, 246], [236, 324], at("main", "r", -13)),
  "reader>pending": curve(at("reader", "l", 24), [238, 256], [238, 432], at("pending", "r", -10)),
  "w1>pending": curve(at("w1", "l", 24), [240, 361], [240, 442], at("pending", "r")),
  "w2>pending": curve(at("w2", "l", 20), [238, 452], [238, 452], at("pending", "r", 10)),
  "reader>marks": curve(at("reader", "l", 30), [236, 262], [236, 522], at("marks", "r", -8)),
  "w1>marks": curve(at("w1", "l", 30), [238, 367], [238, 530], at("marks", "r")),
  "w2>marks": curve(at("w2", "l", 30), [240, 462], [240, 538], at("marks", "r", 8)),
  "reader>companies": via(at("reader", "r", -20), 135, at("companies", "l")),
  "reader>chat": via(at("reader", "r", -28), 135, at("chat", "l")),
  "reader>s4": curve(at("reader", "r", -14), [433, 218], [433, 95], at("s4", "l")),
  "s9>reader": curve(at("s9", "l"), [433, 495], [433, 246], at("reader", "r", 14)),
  "reader>s17": curve(at("reader", "r", 26), [431, 258], [431, 600], at("s17", "l", -10)),
  "w1>s10": via(at("w1", "r", -10), 295, at("s10", "l")),
  "w2>s10": via(at("w2", "r", -10), 375, at("s10", "l", 10)),
  "w1>s14": via(at("w1", "r", 10), 375, at("s14", "l")),
  "w2>s15": via(at("w2", "r", 10), 455, at("s15", "l")),
  "s13>w1": via(at("s13", "l", 10), 375, at("w1", "r", 20)),
  "s4>s5": line(at("s4", "b"), at("s5", "t")),
  "s5>s6": line(at("s5", "b"), at("s6", "t")),
  "s6>s7": line(at("s6", "b"), at("s7", "t")),
  "s7>s8": line(at("s7", "b"), at("s8", "t")),
  "s8>s9": line(at("s8", "b"), at("s9", "t")),
  "s10>s11": line(at("s10", "b"), at("s11", "t")),
  "s11>s12": line(at("s11", "b"), at("s12", "t")),
  "s12>s13": line(at("s12", "b"), at("s13", "t")),
  "s17>pending": curve(at("s17", "l", -14), [330, 596], [250, 452], at("pending", "r", 14)),
  "s17>dead": line(at("s17", "l", 10), at("dead", "r")),
  "s17>marks": curve(at("s17", "l"), [330, 610], [250, 540], at("marks", "r", 14)),
  "s4>circulars": out("s4", "circulars"),
  "s5>circulars": out("s5", "circulars", 6),
  "s5>s3": out("s5", "s3", -12),
  "s5>ocr": out("s5", "ocr", -6),
  "s5>ocrpages": out("s5", "ocrpages", 12),
  "s6>chat": out("s6", "chat", -6),
  "s6>circulars": out("s6", "circulars", 6),
  "s7>emb": out("s7", "emb", -6),
  "s7>circulars": out("s7", "circulars", 6),
  "s8>companies": out("s8", "companies", -6),
  "s8>assessments": out("s8", "assessments", 6),
  "s10>companies": out("s10", "companies", -12),
  "s10>chat": out("s10", "chat", -4),
  "s10>assessments": out("s10", "assessments", 12),
  "s11>policies": out("s11", "policies", -10),
  "s11>checks": out("s11", "checks"),
  "s11>gaps": out("s11", "gaps", 10),
  "s12>policies": out("s12", "policies", -10),
  "s12>chat": out("s12", "chat", -18),
  "s12>checks": out("s12", "checks", 2),
  "s12>gaps": out("s12", "gaps", 12),
  "s13>assessments": out("s13", "assessments"),
  "s14>policies": out("s14", "policies", -12),
  "s14>emb": out("s14", "emb", -20),
  "s14>assessments": out("s14", "assessments", -4),
  "s14>chat": out("s14", "chat", 4),
  "s14>checks": out("s14", "checks", 12),
  "s15>companies": out("s15", "companies", -8),
  "s15>assessments": out("s15", "assessments", 8),
  "s17>circulars": out("s17", "circulars"),
};

const tables = {
  settings: { title: "its settings", store: "config.py", cols: ["setting", "value"] },
  pdfPending: { title: "PDF lane · pending list", store: "Redis", cols: ["task id", "the task", "owner", "idle", "handed out"] },
  mainPending: { title: "main lane · pending list", store: "Redis", cols: ["task id", "the task", "owner", "idle", "handed out"] },
  marks: { title: "marks", store: "Redis", cols: ["key", "expires"] },
  heartbeat: { title: "the task's line, minute by minute", store: "Redis", cols: ["time", "what happens", "idle"] },
  circulars: { title: "circulars", store: "Postgres", cols: ["id", "status", "text", "addressed_to", "summary", "requirements", "embedding"] },
  ocrPages: { title: "ocr_pages", store: "Postgres", cols: ["sha256", "page", "text"] },
  assessments: { title: "assessments", store: "Postgres", cols: ["company", "circular", "status", "applicable", "applies_reason"] },
  scores: { title: "the scores", store: "worked out, not saved", cols: ["policy", "score", "goes to step 12?"] },
  checks: { title: "policy_checks", store: "Postgres", cols: ["circular", "policy", "version", "score", "out of date"] },
  gaps: { title: "gaps · gap_events", store: "Postgres", cols: ["table", "new row"] },
  cost: { title: "what circular 98 cost", store: "in total", cols: ["what", "how many"] },
  policies: { title: "policies", store: "Postgres", cols: ["code", "version", "embedding", "checked_at"] },
  producers: { title: "who queues what", store: "step 16", cols: ["something happens", "who queues", "the task (lane)"] },
  redisDown: { title: "if Redis can't take a task", store: "step 16", cols: ["who was queueing", "what it does"] },
  kinds: { title: "three kinds of failure", store: "failures.py", cols: ["kind", "for example", "what happens to the task"] },
  dead: { title: "the copy in rci:dead", store: "Redis", cols: ["field", "value"] },
  rerun: { title: "how failed work is run again", store: "step 17", cols: ["what failed", "how to run it again", "it carries on from"] },
  died: { title: "when the task comes back", store: "step 18", cols: ["it died…", "the worker…"] },
};

const CIRC_NEW = ["98", "new", "(empty)", "", "", "", ""];
const TEXT = "RESERVE BANK OF INDIA … (12,408 characters)";
const SUMMED = ["98", "parsed", TEXT, "All Regulated Entities… NBFCs…", "RBI designates a new terrorist organisation…", "[\"Report accounts … to FIU-IND\", …]", ""];
const READ = ["98", "read", TEXT, SUMMED[3], SUMMED[4], SUMMED[5], "[0.021, -0.013, …]"];
const OLD = ["41", "skipped", "(empty)", "", "", "", ""];
const A1 = (status, applicable = "", reason = "") => ["1", "98", status, applicable, reason];
const A2 = (status, applicable = "", reason = "") => ["2", "98", status, applicable, reason];
const WHY1 = "Addressed to NBFCs, and the company is an NBFC.";
const WHY2 = "Addressed to banks and NBFCs; the company is a stock broker.";
const KYC = ["98", "POL-KYC", "1", "0.82", "yes"];
const DRP = ["98", "POL-DRP", "1", "0.58", "no"];
const DLP = ["98", "POL-DLP", "1", "0.55", "no"];
const MARK_READ = ["rci:queued:circular_id=98:type=circular.read", "in a day at most"];
const PENDING_98 = (idle, owner = READER, times = "1") => ["1790831159691-0", "circular.read, circular 98", owner, idle, times];

const steps = [
  // ── The worker itself (INTERNALS steps 1 to 3) ──
  {
    story: 0, ref: "step 1", dur: 7400, focus: ["reader", "w1", "w2"], tables: ["settings"],
    title: "Start up",
    text: "Each copy reads its settings (no Gemini key: it stops), makes any missing table, asks Gemini one test question, connects to Redis and names itself, like e02ff2af94f5-1.",
    code: "main(), check_gemini() · worker/main.py · init_db() · common/db.py",
    moves: [["CREATE missing tables", "reader>companies", 0.05, 0.34, "data"], ["a test question", "reader>chat", 0.38, 0.62, "ext"],
            ["connect, name e02f…-1", "reader>pdf", 0.66, 0.88, "queue"]],
    marks: [
      [0.02, { sub: { reader: "starting…", w1: "starting…", w2: "starting…" } }],
      [0.9, { sub: { reader: W, w1: W, w2: W },
              log: [["log", `INFO worker ${READER}: lanes pdf, using gemini-3.5-flash, waiting for tasks`],
                    ["log", `INFO worker ${W1}: lanes main, using gemini-3.5-flash, waiting for tasks`],
                    ["log", `INFO worker ${W2}: lanes main, using gemini-3.5-flash, waiting for tasks`]] }],
    ],
  },
  {
    story: 0, ref: "step 1", dur: 6400, focus: ["reader", "w1", "w2", "pdf", "main"], tables: ["settings"],
    title: "One loop per lane",
    text: "A loop starts for each lane in LANES, in its own thread: the reader takes the PDF lane, worker 1 and worker 2 the main lane. If a loop dies, the program exits and Docker restarts it.",
    code: "lanes(), serve() · worker/main.py",
    moves: [["LANES=pdf", "reader>pdf", 0.08, 0.5, "queue"], ["LANES=main", "w1>main", 0.18, 0.6, "queue"], ["LANES=main", "w2>main", 0.28, 0.7, "queue"]],
  },
  {
    story: 0, ref: "step 2", dur: 6800, focus: ["watcher", "pdf", "marks"], tables: ["marks", "circulars"],
    title: "A task is a note on a lane",
    text: "The watcher saved circular 98 and put a note on the PDF lane: read 98, a type and an id, never the data. Its mark stops anyone adding the same note twice.",
    code: "enqueue() · common/queue.py",
    moves: [["SET mark", "watcher>pdf", 0.06, 0.4, "queue"], ["read 98", "watcher>pdf", 0.46, 0.82, "queue"]],
    marks: [
      [0.4, { rows: { marks: [MARK_READ] }, sub: { marks: "circular.read 98" },
              log: ["redis", "SET rci:queued:circular_id=98:type=circular.read 1 NX EX 86400 → OK"] }],
      [0.82, { slots: { pdf: ["read 98"] }, log: ["redis", "XADD rci:tasks:pdf * type circular.read circular_id 98 → 1790831159691-0"] }],
    ],
  },
  {
    story: 0, ref: "step 2", dur: 6800, focus: ["reader", "pending", "pdf"], tables: ["pdfPending"],
    title: "Where to look, 1: my own pending list",
    text: "Each turn the loop first makes sure the group exists (XGROUP CREATE). Then XREADGROUP … 0: a task it was handed before but never finished, after a retry or a restart. None.",
    code: "serve(), next_task() · worker/main.py",
    moves: [["XGROUP CREATE", "reader>pdf", 0.04, 0.26, "queue"], ["XREADGROUP 0", "reader>pending", 0.34, 0.6, "queue"],
            ["none", "pending>reader", 0.66, 0.92, "queue"]],
    marks: [
      [0.26, { log: ["redis", "XGROUP CREATE rci:tasks:pdf workers 0 MKSTREAM → BUSYGROUP (it exists: fine)"] }],
      [0.6, { log: ["redis", `XREADGROUP GROUP workers ${READER} COUNT 1 STREAMS rci:tasks:pdf 0 → (nothing)`] }],
    ],
  },
  {
    story: 0, ref: "step 2", dur: 6400, focus: ["reader", "pending"], tables: ["pdfPending"],
    title: "2: a task a dead worker left",
    text: "Then XAUTOCLAIM: a task on another worker's pending list that nobody has touched for 5 minutes belongs to a worker that died, and moves here. None.",
    code: "next_task(), CLAIM_IDLE_SECONDS · worker/main.py",
    moves: [["XAUTOCLAIM 5 min", "reader>pending", 0.06, 0.42, "queue"], ["none", "pending>reader", 0.52, 0.88, "queue"]],
    marks: [[0.42, { log: ["redis", `XAUTOCLAIM rci:tasks:pdf workers ${READER} 300000 0-0 COUNT 1 → (nothing)`] }]],
  },
  {
    story: 0, ref: "step 2", dur: 7000, focus: ["pdf", "reader", "pending"], tables: ["pdfPending"],
    title: "3: a new task",
    text: "Then XREADGROUP … >: wait up to 5 s for a task nobody has had. Redis hands over read 98 and, in the same moment, writes the reader's name next to it on the pending list.",
    code: "next_task() · worker/main.py",
    moves: [["XREADGROUP >", "reader>pdf", 0.04, 0.3, "queue"], ["read 98", "pdf>reader", 0.38, 0.72, "queue"]],
    marks: [
      [0.38, { slots: { pdf: [] } }],
      [0.72, { sub: { reader: "read 98", pending: "98 → e02f…-1 · 0 s" }, rows: { pdfPending: [PENDING_98("0 s")] },
               log: ["redis", `XREADGROUP GROUP workers ${READER} COUNT 1 BLOCK 5000 STREAMS rci:tasks:pdf > → 1790831159691-0 {type: circular.read, circular_id: 98}`] }],
    ],
  },
  {
    story: 0, ref: "step 3", dur: 8400, focus: ["reader", "pending"], tables: ["heartbeat", "pdfPending"],
    title: "Keep touching it",
    text: "Redis can't tell a busy worker from a dead one, only how long a task sat untouched. So a helper touches it every minute (XCLAIM): a long PDF never looks abandoned.",
    code: "keep_claimed(), HEARTBEAT_SECONDS · worker/main.py",
    moves: [["XCLAIM: still mine", "reader>pending", 0.36, 0.56, "queue"], ["XCLAIM again", "reader>pending", 0.7, 0.9, "queue"]],
    marks: [
      [0.04, { rows: { heartbeat: [["10:00:00", "Redis hands the task to e02f…-1", "0 s"]] } }],
      [0.2, { rows: { heartbeat: [["10:00:00", "Redis hands the task to e02f…-1", "0 s"], ["10:00:59", "still reading page 2", "59 s"]],
                      pdfPending: [PENDING_98("59 s")] }, sub: { pending: "98 → e02f…-1 · 59 s" } }],
      [0.56, { rows: { heartbeat: [["10:00:00", "Redis hands the task to e02f…-1", "0 s"], ["10:00:59", "still reading page 2", "59 s"],
                                   ["10:01:00", "the helper touches it", "0 s"]],
                       pdfPending: [PENDING_98("0 s")] }, sub: { pending: "98 → e02f…-1 · 0 s" },
               log: ["redis", `XCLAIM rci:tasks:pdf workers ${READER} 0 1790831159691-0 JUSTID`] }],
      [0.9, { rows: { heartbeat: [["10:00:00", "Redis hands the task to e02f…-1", "0 s"], ["10:00:59", "still reading page 2", "59 s"],
                                  ["10:01:00", "the helper touches it", "0 s"], ["10:02:00", "the helper touches it again", "0 s"]] } }],
    ],
  },
  {
    story: 0, ref: "step 3", dur: 6400, focus: ["reader", "s4"], tables: ["pdfPending"],
    title: "Which job?",
    text: "The task's type picks the function: circular.read runs steps 4 to 9, circular.assess 10 to 13, policy.check 14, company.refresh 15. No locks: each task goes to one worker only.",
    code: "run_task(), TASKS · worker/main.py",
    moves: [["read_circular(98)", "reader>s4", 0.2, 0.75, "svc"]],
  },

  // ── Reading a circular (steps 4 to 9), the reader ──
  {
    story: 1, ref: "step 4", dur: 6800, focus: ["s4", "circulars"], tables: ["circulars"],
    title: "Skip it or read it?",
    text: "It reads circular 98's row. Older than 30 days (LOOKBACK_DAYS): skipped, no OCR, no Gemini. Marked failed: left alone. 98 is new and published today, so it's read.",
    code: "read_circular(), cutoff() · worker/pipeline.py",
    moves: [["status? date?", "s4>circulars", 0.05, 0.4, "data"], ["new · today", "circulars>s4", 0.5, 0.88, "data"]],
    marks: [[0.4, { log: ["sql", "SELECT * FROM circulars WHERE id = 98 → status 'new', published today"] }]],
  },
  {
    story: 1, ref: "step 4", dur: 7400, focus: ["s4", "s17", "circulars"], tables: ["circulars"],
    title: "Where skipped and failed come from",
    text: "Skipped is set right here: circular 41, from 90 days ago, costs nothing. Failed is set only by give_up() in step 17. Reprocess runs either again, carrying on from what's saved.",
    code: "read_circular() · worker/pipeline.py · give_up() · worker/main.py",
    moves: [["41: 90 days old", "s4>circulars", 0.12, 0.55, "ask"]],
    marks: [[0.55, { rows: { circulars: [CIRC_NEW, OLD] },
                     log: [["sql", "UPDATE circulars SET status = 'skipped' WHERE id = 41"], ["sql", "COMMIT"]] }]],
  },
  {
    story: 1, ref: "step 5", dur: 6800, focus: ["s5", "circulars"], tables: ["circulars"],
    title: "The same PDF seen before?",
    text: "If another circular has the same fingerprint (sha256) and its text already, the text is just copied: no OCR at all. Circular 98's PDF is new.",
    code: "twin() · worker/pipeline.py",
    moves: [["read it", "s4>s5", 0.03, 0.2, "ask"], ["same sha256?", "s5>circulars", 0.26, 0.56, "data"], ["none", "circulars>s5", 0.62, 0.92, "data"]],
    marks: [[0.56, { log: ["sql", `SELECT * FROM circulars WHERE sha256 = '${SHA}' AND id <> 98 AND text IS NOT NULL → (none)`] }]],
  },
  {
    story: 1, ref: "step 5", dur: 7000, focus: ["s5", "ocrpages", "s3"], tables: ["ocrPages"],
    title: "Pages read before? Then the PDF",
    text: "ocr_pages holds pages an earlier try already read: none yet. The PDF comes from S3, straight into memory: 3 pages.",
    code: "ocr_text() · worker/pipeline.py · get_pdf() · worker/storage.py",
    moves: [["saved pages?", "s5>ocrpages", 0.03, 0.24, "data"], ["none", "ocrpages>s5", 0.28, 0.46, "data"],
            ["GET", "s5>s3", 0.52, 0.7, "data"], ["PDF, 3 pages", "s3>s5", 0.74, 0.94, "data"]],
    marks: [
      [0.24, { log: ["sql", `SELECT page, text FROM ocr_pages WHERE sha256 = '${SHA}' → (none)`] }],
      [0.7, { log: ["s3", `GET s3://rci/rbi/${SHA}.pdf`] }],
    ],
  },
  {
    story: 1, ref: "step 5", dur: 7400, focus: ["s5", "ocr", "ocrpages"], tables: ["ocrPages"],
    title: "Page 1: a picture, its text, saved",
    text: "Each page is drawn as a 200 DPI picture and sent to OCR on the GPU. Its text goes into ocr_pages the moment it comes back, before the next page.",
    code: "pages(), ocr_page(), remove_det() · worker/ocr.py",
    moves: [["page 1", "s5>ocr", 0.04, 0.3, "gpu"], ["text", "ocr>s5", 0.36, 0.6, "gpu"], ["save page 1", "s5>ocrpages", 0.66, 0.9, "data"]],
    marks: [
      [0.3, { log: ["ocr", "POST http://ocr:8000/v1/chat/completions  page 1 as a 200 DPI PNG, \"<image>document parsing.\""] }],
      [0.9, { rows: { ocrPages: [[SHA, "0", "RESERVE BANK OF INDIA …"]] }, sub: { ocrpages: "3f9a… · 1 page" },
              log: [["sql", `INSERT INTO ocr_pages (sha256, page, text) VALUES ('${SHA}', 0, 'RESERVE BANK OF INDIA …')`], ["sql", "COMMIT"]] }],
    ],
  },
  {
    story: 1, ref: "step 5", dur: 7800, focus: ["s5", "ocr", "ocrpages"], tables: ["ocrPages"],
    title: "Page 2, then a blank page 3",
    text: "Page 2 the same way. Page 3 has no text, no images and no drawings: it's never sent to the GPU, and is saved as empty text.",
    code: "pages(), blank() · worker/ocr.py",
    moves: [["page 2", "s5>ocr", 0.03, 0.24, "gpu"], ["text", "ocr>s5", 0.28, 0.48, "gpu"], ["save page 2", "s5>ocrpages", 0.52, 0.7, "data"],
            ["page 3: blank", "s5>ocrpages", 0.76, 0.94, "data"]],
    marks: [
      [0.7, { rows: { ocrPages: [[SHA, "0", "RESERVE BANK OF INDIA …"], [SHA, "1", "2. Regulated entities shall …"]] }, sub: { ocrpages: "3f9a… · 2 pages" },
              log: [["ocr", "POST http://ocr:8000/v1/chat/completions  page 2"], ["sql", `INSERT INTO ocr_pages … VALUES ('${SHA}', 1, '2. Regulated entities shall …')`]] }],
      [0.94, { rows: { ocrPages: [[SHA, "0", "RESERVE BANK OF INDIA …"], [SHA, "1", "2. Regulated entities shall …"], [SHA, "2", "\"\" (blank)"]] },
               sub: { ocrpages: "3f9a… · 3 pages" },
               log: [["app", "page 3: no text, images or drawings → blank, not sent to the GPU"], ["sql", `INSERT INTO ocr_pages … VALUES ('${SHA}', 2, '')`]] }],
    ],
  },
  {
    story: 1, ref: "step 5", dur: 6800, focus: ["s5", "ocrpages"], tables: ["ocrPages"],
    title: "Had it stopped on page 3",
    text: "Each page is saved before the next, so had the reader stopped on page 3, the next try would start at page 3, not page 1. A saved page never goes to the GPU again.",
    code: "ocr_text() · worker/pipeline.py",
    moves: [["pages 1-2 saved: skip", "ocrpages>s5", 0.15, 0.6, "data"]],
    marks: [[0.6, { log: ["log", "INFO #98: 2 pages OCR'd before, carrying on   (what the log would say after a restart)"] }]],
  },
  {
    story: 1, ref: "step 5", dur: 7000, focus: ["s5", "circulars", "ocrpages"], tables: ["circulars", "ocrPages"],
    title: "Join them into the text",
    text: "The pages are joined into circular 98's text, 12,408 characters, and its status becomes parsed. The 3 ocr_pages rows are deleted in the same commit.",
    code: "read_circular(), ocr_text() · worker/pipeline.py",
    moves: [["the text", "s5>circulars", 0.05, 0.45, "data"], ["DELETE 3 rows", "s5>ocrpages", 0.3, 0.66, "data"]],
    marks: [[0.66, {
      rows: { circulars: [["98", "parsed", TEXT, "", "", "", ""], OLD], ocrPages: [] },
      sub: { circulars: "98 · parsed", ocrpages: "empty" },
      log: [["sql", "UPDATE circulars SET text = 'RESERVE BANK OF INDIA …', status = 'parsed' WHERE id = 98"],
            ["sql", `DELETE FROM ocr_pages WHERE sha256 = '${SHA}'`], ["sql", "COMMIT"], ["log", "INFO #98 parsed: 12408 chars"]],
    }]],
  },
  {
    story: 1, ref: "step 6", dur: 7600, focus: ["s6", "chat", "circulars"], tables: ["circulars"],
    title: "Gemini answers three questions",
    text: "Who is it for? What does it change? What must be done, with its numbers and deadlines as written? Gemini must answer in a fixed format, or it's asked again.",
    code: "summarize(), CircularSummary · worker/llm.py",
    moves: [["summarise it", "s5>s6", 0.02, 0.16, "ext"], ["the text", "s6>chat", 0.2, 0.44, "ext"], ["JSON answer", "chat>s6", 0.5, 0.72, "ext"],
            ["save", "s6>circulars", 0.76, 0.94, "data"]],
    marks: [
      [0.72, { log: ["llm", "summarize(98) → {addressed_to: 'All Regulated Entities… NBFCs…', summary: 'RBI designates a new terrorist organisation…', requirements: […]}"] }],
      [0.94, { rows: { circulars: [SUMMED, OLD] }, sub: { circulars: "98 · summary saved" },
               log: [["sql", "UPDATE circulars SET addressed_to = …, summary = …, requirements = … WHERE id = 98"], ["sql", "COMMIT"],
                     ["log", "INFO #98 read: addressed to 'All Regulated Entities…'"]] }],
    ],
  },
  {
    story: 1, ref: "step 7", dur: 7400, focus: ["s7", "emb", "circulars"], tables: ["circulars"],
    title: "Turn the summary into numbers",
    text: "An embedding: 768 numbers that capture what a text is about, so similar texts get similar numbers. Made once, used for every company. Circular 98 is now read.",
    code: "embed_circular() · worker/pipeline.py · embed() · worker/llm.py",
    moves: [["into numbers", "s6>s7", 0.02, 0.16, "ext"], ["title + summary", "s7>emb", 0.2, 0.44, "ext"], ["768 numbers", "emb>s7", 0.5, 0.72, "ext"],
            ["save", "s7>circulars", 0.76, 0.94, "data"]],
    marks: [
      [0.72, { log: ["llm", "embed([title + summary + obligations], RETRIEVAL_QUERY) → [0.021, -0.013, …] (768 numbers)"] }],
      [0.94, { rows: { circulars: [READ, OLD] }, sub: { circulars: "98 · read" },
               log: [["sql", "UPDATE circulars SET embedding = […], status = 'read' WHERE id = 98"], ["sql", "COMMIT"]] }],
    ],
  },
  {
    story: 1, ref: "step 8", dur: 7400, focus: ["s8", "companies", "assessments"], tables: ["assessments"],
    title: "A to-do for each company",
    text: "Each company decides for itself, so each gets an assessment, pending: not checked yet. The function hands back one circular.assess per company, to queue in step 9.",
    code: "add_assessments(), pending() · worker/pipeline.py",
    moves: [["a to-do each", "s7>s8", 0.02, 0.14, "data"], ["which companies?", "s8>companies", 0.18, 0.4, "data"], ["1 and 2", "companies>s8", 0.44, 0.62, "data"],
            ["2 rows", "s8>assessments", 0.68, 0.92, "data"]],
    marks: [[0.92, { rows: { assessments: [A1("pending"), A2("pending")] }, sub: { assessments: "98: 1 and 2 pending" },
                     log: [["sql", "INSERT INTO assessments (company_id, circular_id, status) VALUES (1, 98, 'pending'), (2, 98, 'pending') ON CONFLICT DO NOTHING"],
                           ["sql", "COMMIT"]] }]],
  },
  {
    story: 1, ref: "step 9", dur: 7200, focus: ["s9", "reader", "marks"], tables: ["marks"],
    title: "Finish 1 and 2: stop touching, delete the mark",
    text: "Every task ends the same way. The helper stops touching it. Then its mark is deleted, so the same task can be queued again later, by Reprocess for example.",
    code: "run_task() · worker/main.py",
    moves: [["finish", "s8>s9", 0.02, 0.16, "queue"], ["finish", "s9>reader", 0.2, 0.46, "queue"], ["DEL mark", "reader>marks", 0.54, 0.86, "queue"]],
    marks: [[0.86, { rows: { marks: [] }, sub: { marks: "none" }, log: ["redis", "DEL rci:queued:circular_id=98:type=circular.read"] }]],
  },
  {
    story: 1, ref: "step 9", dur: 7600, focus: ["reader", "marks", "main"], tables: ["marks"],
    title: "Finish 3: queue the next tasks",
    text: "Each new task gets its own mark first (kept a day at most, in case a worker dies first), then goes on the main lane: check 98 for company 1, and for company 2.",
    code: "run_task() · worker/main.py · enqueue() · common/queue.py",
    moves: [["SET 2 marks", "reader>marks", 0.05, 0.4, "queue"], ["XADD ×2", "reader>main", 0.48, 0.86, "queue"]],
    marks: [
      [0.4, { rows: { marks: [["rci:queued:circular_id=98:company_id=1:type=circular.assess", "in a day at most"],
                              ["rci:queued:circular_id=98:company_id=2:type=circular.assess", "in a day at most"]] },
              sub: { marks: "circular.assess 98 ×2" },
              log: ["redis", "SET rci:queued:circular_id=98:company_id=1:type=circular.assess 1 NX EX 86400 → OK  (and company 2)"] }],
      [0.86, { slots: { main: ["98 · 1", "98 · 2"] },
               log: [["redis", "XADD rci:tasks * type circular.assess company_id 1 circular_id 98"],
                     ["redis", "XADD rci:tasks * type circular.assess company_id 2 circular_id 98"]] }],
    ],
  },
  {
    story: 1, ref: "step 9", dur: 7400, focus: ["reader", "pending"], tables: ["pdfPending"],
    title: "Finish 4: XACK",
    text: "XACK takes the task off the pending list for good. Why last? Dying before it only means the task runs once more, finds its work saved, and its copies are dropped by their marks.",
    code: "run_task() · worker/main.py",
    moves: [["XACK", "reader>pending", 0.12, 0.6, "ok"]],
    marks: [[0.6, { rows: { pdfPending: [] }, sub: { reader: W, pending: NOBODY },
                    log: ["redis", "XACK rci:tasks:pdf workers 1790831159691-0"] }]],
  },

  // ── Checking it for one company (steps 10 to 13), the workers ──
  {
    story: 2, ref: "step 10", dur: 7400, focus: ["main", "w1", "w2"], tables: ["mainPending"],
    title: "Two workers, one company each",
    text: "Worker 1 takes company 1's note and worker 2 company 2's, at the same moment. Each note goes to exactly one worker, and never waits behind a PDF.",
    code: "next_task(), run_task() · worker/main.py",
    moves: [["98 · 1", "main>w1", 0.05, 0.38, "queue"], ["98 · 2", "main>w2", 0.1, 0.43, "queue"],
            ["assess(1, 98)", "w1>s10", 0.5, 0.88, "svc"], ["assess(2, 98)", "w2>s10", 0.55, 0.92, "svc"]],
    marks: [
      [0.05, { slots: { main: ["98 · 2"] } }], [0.1, { slots: { main: [] } }],
      [0.43, { sub: { w1: "98 · company 1", w2: "98 · company 2", pending: "2 on the main lane" },
               rows: { mainPending: [["1790831161204-0", "circular.assess, 1 · 98", W1, "0 s", "1"],
                                     ["1790831161207-0", "circular.assess, 2 · 98", W2, "0 s", "1"]] },
               log: [["redis", `XREADGROUP GROUP workers ${W1} COUNT 1 BLOCK 5000 STREAMS rci:tasks > → {type: circular.assess, company_id: 1, circular_id: 98}`],
                     ["redis", `XREADGROUP GROUP workers ${W2} … > → {type: circular.assess, company_id: 2, circular_id: 98}`]] }],
    ],
  },
  {
    story: 2, ref: "step 10", dur: 8200, focus: ["s10", "companies", "chat", "assessments"], tables: ["assessments"],
    title: "Does it apply to this company?",
    text: "Gemini reads each company's description and the start of the circular. Company 1, an NBFC: yes. Company 2, a stock broker: no, so its check ends here.",
    code: "assess() · worker/pipeline.py · check_applicability() · worker/llm.py",
    moves: [["descriptions", "s10>companies", 0.02, 0.22, "data"], ["applies? ×2", "s10>chat", 0.26, 0.48, "ext"],
            ["yes · no", "chat>s10", 0.52, 0.72, "ext"], ["answers", "s10>assessments", 0.76, 0.94, "data"]],
    marks: [
      [0.72, { log: [["llm", `check_applicability(company 1, 98) → {applies_to_company: true, reason: '${WHY1}'}`],
                     ["llm", `check_applicability(company 2, 98) → {applies_to_company: false, reason: '${WHY2}'}`]] }],
      [0.94, { rows: { assessments: [A1("pending", "true", WHY1), A2("pending", "false", WHY2)] }, sub: { assessments: "98: 1 yes · 2 no" },
               log: [["sql", "UPDATE assessments SET applicable = true, applies_reason = '…' WHERE company_id = 1 AND circular_id = 98"],
                     ["sql", "UPDATE assessments SET applicable = false, … WHERE company_id = 2 AND circular_id = 98"], ["sql", "COMMIT"]] }],
    ],
  },
  {
    story: 2, ref: "step 10", dur: 6400, focus: ["s10", "s15", "companies"], tables: ["assessments"],
    title: "No description yet? Not checked",
    text: "A company that hasn't described itself isn't asked: its circulars show Analysed, Not checked, until it writes one (step 15). A failure here fails only this company's check.",
    code: "assess() · worker/pipeline.py",
    moves: [["described?", "s10>companies", 0.15, 0.6, "ask"]],
  },
  {
    story: 2, ref: "step 11", dur: 8000, focus: ["s11", "policies"], tables: ["scores"],
    title: "Find the closest policies",
    text: "Asking Gemini about every policy would be slow and costly. So company 1's RBI policies are compared by their numbers: plain arithmetic, no Gemini. The 3 closest go on.",
    code: "match(), cosine() · worker/pipeline.py",
    moves: [["company 1 goes on", "s10>s11", 0.02, 0.16, "data"], ["RBI policies?", "s11>policies", 0.2, 0.42, "data"],
            ["4 + their numbers", "policies>s11", 0.48, 0.72, "data"]],
    marks: [
      [0.42, { log: ["sql", "SELECT * FROM policies WHERE company_id = 1 → 4 tagged RBI, all embedded with gemini-embedding-001"] }],
      [0.8, { rows: { scores: [["POL-KYC", "0.82", "yes"], ["POL-DRP", "0.58", "yes"], ["POL-DLP", "0.55", "yes"], ["POL-IT", "0.31", "no: not in the top 3"]] },
              sub: { s11: "KYC DRP DLP" },
              log: ["app", "cosine(98, each policy's best chunk): POL-KYC 0.82 · POL-DRP 0.58 · POL-DLP 0.55 · POL-IT 0.31"] }],
    ],
  },
  {
    story: 2, ref: "step 11", dur: 7000, focus: ["s11", "checks", "gaps"], tables: ["checks"],
    title: "Never ask the same question twice",
    text: "A policy already asked about for 98 at its current version, or with a gap from 98, is skipped. A policy embedded with an older model is embedded again first.",
    code: "match(), embed_policy() · worker/pipeline.py",
    moves: [["asked before?", "s11>checks", 0.04, 0.26, "data"], ["no", "checks>s11", 0.3, 0.48, "data"],
            ["a gap from 98?", "s11>gaps", 0.54, 0.74, "data"], ["no", "gaps>s11", 0.78, 0.96, "data"]],
    marks: [
      [0.26, { log: ["sql", "SELECT policy_id, policy_version FROM policy_checks WHERE circular_id = 98 → (none)"] }],
      [0.74, { log: ["sql", "SELECT policy_id FROM gaps WHERE circular_id = 98 → (none)"] }],
    ],
  },
  {
    story: 2, ref: "step 12", dur: 8000, focus: ["s12", "policies", "chat"], tables: ["checks"],
    title: "POL-KYC: out of date?",
    text: "Gemini reads the circular's obligations, the policy and its controls: does the policy still meet what the circular asks? POL-KYC doesn't, and it's serious: severity high.",
    code: "judge_policy() · worker/pipeline.py · assess(), Verdict · worker/llm.py",
    moves: [["the top 3", "s11>s12", 0.02, 0.14, "ext"], ["controls", "s12>policies", 0.18, 0.36, "data"],
            ["POL-KYC v1?", "s12>chat", 0.42, 0.64, "ext"], ["out of date · high", "chat>s12", 0.68, 0.92, "gap"]],
    marks: [
      [0.36, { log: ["sql", "SELECT * FROM controls WHERE policy_id = 9"] }],
      [0.92, { sub: { s12: "KYC: out of date" },
               log: ["llm", "assess(98, POL-KYC v1) → {impacted: true, severity: 'high', missing_from_policy: 'The policy does not require reporting to FIU-IND…', draft_change: 'Add clause 2A: …'}"] }],
    ],
  },
  {
    story: 2, ref: "step 12", dur: 8400, focus: ["s12", "checks", "gaps"], tables: ["checks", "gaps"],
    title: "The verdict and its gap, together",
    text: "The answer goes in policy_checks, with a gap for the policy's owner: due in 7 days because it's high, with what's missing and a draft of the new wording. Both or neither.",
    code: "judge_policy(), DUE_DAYS · worker/pipeline.py",
    moves: [["verdict", "s12>checks", 0.05, 0.4, "data"], ["gap + its first event", "s12>gaps", 0.3, 0.7, "gap"]],
    marks: [[0.7, {
      rows: { checks: [KYC], gaps: [["gaps", "company 1 · POL-KYC · high · Head of Compliance · due in 7 days · draft \"Add clause 2A: …\""],
                                    ["gap_events", "agent · opened · \"The policy does not require reporting to FIU-IND…\""]] },
      sub: { checks: "98 × POL-KYC: yes", gaps: "POL-KYC · high" },
      log: [["sql", "INSERT INTO policy_checks (circular_id, policy_id, policy_version, similarity, impacted) VALUES (98, 9, 1, 0.82, true)"],
            ["sql", "INSERT INTO gaps (company_id, circular_id, policy_id, severity, owner, due_date, draft_change, …) VALUES (1, 98, 9, 'high', …, today + 7, …)"],
            ["sql", "INSERT INTO gap_events (gap_id, actor, action, note) VALUES (…, 'agent', 'opened', 'The policy does not require reporting to FIU-IND…')"],
            ["sql", "COMMIT"], ["log", "INFO #98 vs POL-KYC v1 (0.82): GAP"]],
    }]],
  },
  {
    story: 2, ref: "step 12", dur: 8400, focus: ["s12", "chat", "checks"], tables: ["checks"],
    title: "POL-DRP and POL-DLP: up to date",
    text: "The other two are asked one by one, each answer saved before the next question, so a retry only asks what's left. Due dates when out of date: high 7 days, medium 30, low 60.",
    code: "judge_policy() · worker/pipeline.py",
    moves: [["POL-DRP v1?", "s12>chat", 0.02, 0.18, "ext"], ["up to date", "chat>s12", 0.2, 0.36, "ok"], ["verdict", "s12>checks", 0.38, 0.5, "data"],
            ["POL-DLP v1?", "s12>chat", 0.54, 0.7, "ext"], ["up to date", "chat>s12", 0.72, 0.86, "ok"], ["verdict", "s12>checks", 0.88, 0.98, "data"]],
    marks: [
      [0.5, { rows: { checks: [KYC, DRP] }, log: ["log", "INFO #98 vs POL-DRP v1 (0.58): up to date"] }],
      [0.98, { rows: { checks: [KYC, DRP, DLP] }, sub: { checks: "98: 3 verdicts", s12: "a verdict, a gap" },
               log: ["log", "INFO #98 vs POL-DLP v1 (0.55): up to date"] }],
    ],
  },
  {
    story: 2, ref: "step 13", dur: 8400, focus: ["s13", "assessments", "w1", "w2"], tables: ["assessments", "mainPending"],
    title: "Mark it done",
    text: "Each company's assessment becomes done, and each worker finishes its task as in step 9: DEL its mark, then XACK. Company 1 now sees the new gap on its Gaps page.",
    code: "assess() · worker/pipeline.py · run_task() · worker/main.py",
    moves: [["done", "s12>s13", 0.02, 0.14, "ok"], ["done ×2", "s13>assessments", 0.18, 0.42, "data"], ["finish", "s13>w1", 0.46, 0.66, "ok"],
            ["DEL · XACK", "w1>pending", 0.7, 0.92, "ok"], ["DEL · XACK", "w2>pending", 0.72, 0.94, "ok"]],
    marks: [
      [0.42, { rows: { assessments: [A1("done", "true", WHY1), A2("done", "false", WHY2)] }, sub: { assessments: "98: both done" },
               log: [["sql", "UPDATE assessments SET status = 'done' WHERE circular_id = 98 AND company_id IN (1, 2)"], ["sql", "COMMIT"],
                     ["log", "INFO #98 for company 1: applies: True, gaps opened: ['POL-KYC']"],
                     ["log", "INFO #98 for company 2: applies: False, gaps opened: none"]] }],
      [0.94, { rows: { mainPending: [] }, sub: { w1: W, w2: W, pending: NOBODY, marks: "none", s11: "top 3, no Gemini" },
               log: [["redis", "DEL rci:queued:circular_id=98:company_id=1:type=circular.assess  (and company 2's)"],
                     ["redis", "XACK rci:tasks workers 1790831161204-0 1790831161207-0"]] }],
    ],
  },
  {
    story: 2, ref: "step 13", dur: 6800, focus: ["s5", "s6", "s7", "s10", "s12"], tables: ["cost"],
    title: "What the whole journey cost",
    text: "For everyone at once: OCR once per page, 1 summary, 1 embedding. Then per company: 1 \"does it apply?\" and, where it applies, up to 3 policy questions.",
    code: "",
    moves: [],
    marks: [[0.1, { rows: { cost: [["OCR", "once per page: 2 pages (page 3 was blank)"], ["Gemini summary", "1, for every company"],
                                   ["embedding", "1, for every company"], ["does it apply?", "1 per company: 2"],
                                   ["policy questions", "up to 3 per company it applies to: 3"]] } }]],
  },

  // ── The other tasks (steps 14 and 15) ──
  {
    story: 3, ref: "step 14", dur: 7600, focus: ["api", "main", "w1", "s14"], tables: ["policies"],
    title: "A policy is added: policy.check",
    text: "Company 1 saves POL-AML in the console. The api saves it first, then queues policy.check on the main lane. The policy's page says Waiting for the worker.",
    code: "create_policy() · api/routes/policies.py",
    moves: [["policy.check", "api>main", 0.04, 0.36, "queue"], ["POL-AML", "main>w1", 0.44, 0.66, "queue"], ["check_policy()", "w1>s14", 0.7, 0.94, "svc"]],
    marks: [
      [0.04, { rows: { policies: [["POL-AML", "1", "(none yet)", "(empty)"]] } }],
      [0.36, { slots: { main: ["POL-AML"] }, sub: { marks: "policy.check 11" },
               log: ["redis", "XADD rci:tasks * type policy.check company_id 1 policy_id 11"] }],
      [0.66, { slots: { main: [] }, sub: { w1: "POL-AML" } }],
    ],
  },
  {
    story: 3, ref: "step 14", dur: 7400, focus: ["s14", "emb", "policies"], tables: ["policies"],
    title: "Turn it into numbers, chunk by chunk",
    text: "A long policy is cut into 5,000-character chunks, and each chunk gets its own 768 numbers. Against a circular, a policy scores its best chunk.",
    code: "embed_policy() · worker/pipeline.py",
    moves: [["the text", "policies>s14", 0.03, 0.22, "data"], ["2 chunks", "s14>emb", 0.28, 0.5, "ext"], ["2 × 768 numbers", "emb>s14", 0.54, 0.74, "ext"],
            ["save", "s14>policies", 0.78, 0.95, "data"]],
    marks: [[0.95, { rows: { policies: [["POL-AML", "1", "[[0.012, …], [0.031, …]]", "(empty)"]] },
                     log: [["sql", "UPDATE policies SET embeddings = […], embedding_model = 'gemini-embedding-001' WHERE id = 11"], ["sql", "COMMIT"],
                           ["log", "INFO embedded POL-AML (2 chunks) with gemini-embedding-001"]] }]],
  },
  {
    story: 3, ref: "step 14", dur: 8400, focus: ["s14", "assessments", "chat", "checks"], tables: ["checks"],
    title: "Check it against recent circulars",
    text: "For each of company 1's circulars of the last 30 days that apply, POL-AML now competes for the top 3. For 98 it's second, 0.71, and never asked before: one Gemini call.",
    code: "check_policy(), match() · worker/pipeline.py",
    moves: [["apply, 30 days", "s14>assessments", 0.02, 0.2, "data"], ["98, …", "assessments>s14", 0.23, 0.38, "data"],
            ["POL-AML v1?", "s14>chat", 0.44, 0.64, "ext"], ["up to date", "chat>s14", 0.68, 0.84, "ok"], ["verdict", "s14>checks", 0.86, 0.98, "data"]],
    marks: [[0.98, { rows: { checks: [KYC, DRP, DLP, ["98", "POL-AML", "1", "0.71", "no"]] }, sub: { checks: "98: 4 verdicts" },
                     log: ["log", "INFO #98 vs POL-AML v1 (0.71): up to date"] }]],
  },
  {
    story: 3, ref: "step 14", dur: 7000, focus: ["s14", "policies", "w1"], tables: ["policies"],
    title: "Checked",
    text: "checked_at is stamped, so the console shows Checked. If the policy was saved again while this ran, it's checked once more, with the new text.",
    code: "check_policy() · worker/pipeline.py",
    moves: [["checked_at", "s14>policies", 0.08, 0.5, "ok"]],
    marks: [[0.5, { rows: { policies: [["POL-AML", "1", "[[0.012, …], [0.031, …]]", "2026-10-01 10:15"]] },
                    sub: { w1: W, marks: "none" },
                    log: [["sql", "UPDATE policies SET checked_at = '2026-10-01 10:15' WHERE id = 11"], ["sql", "COMMIT"],
                          ["log", "INFO POL-AML checked, gaps opened: none"], ["redis", "DEL … · XACK rci:tasks workers …"]] }]],
  },
  {
    story: 3, ref: "step 15", dur: 7400, focus: ["api", "main", "w2", "s15"], tables: ["assessments"],
    title: "A description changes: company.refresh",
    text: "Company 2 rewrites its description. The api saves it and queues company.refresh. Saving the same text, or only a new name, or signing up, queues nothing.",
    code: "set_company() · api/routes/company.py",
    moves: [["company.refresh", "api>main", 0.04, 0.36, "queue"], ["refresh 2", "main>w2", 0.44, 0.66, "queue"],
            ["refresh_company(2)", "w2>s15", 0.7, 0.94, "svc"]],
    marks: [[0.36, { slots: { main: ["refresh 2"] }, log: ["redis", "XADD rci:tasks * type company.refresh company_id 2"] }],
            [0.66, { slots: { main: [] }, sub: { w2: "refresh 2" } }]],
  },
  {
    story: 3, ref: "step 15", dur: 8000, focus: ["s15", "companies", "assessments"], tables: ["assessments"],
    title: "Reset the old answers",
    text: "Every answer company 2 gave before the change goes back to pending, its \"applies\" cleared. An answer given after the change (a circular read since) is kept.",
    code: "refresh_company() · worker/pipeline.py",
    moves: [["changed when?", "s15>companies", 0.03, 0.26, "data"], ["updated_at", "companies>s15", 0.3, 0.5, "data"],
            ["reset", "s15>assessments", 0.56, 0.86, "data"]],
    marks: [[0.86, {
      rows: { assessments: [A1("done", "true", WHY1), ["2", "98", "pending", "(cleared)", ""], ["2", "97", "pending", "(cleared)", ""],
                            ["2", "99", "done", "true", "answered after the change: kept"]] },
      log: [["sql", "UPDATE assessments SET status = 'pending', applicable = NULL, applies_reason = NULL WHERE company_id = 2 AND status <> 'pending' AND updated_at < (company 2's updated_at)"],
            ["sql", "COMMIT"]],
    }]],
  },
  {
    story: 3, ref: "step 15", dur: 8000, focus: ["s15", "assessments", "w2", "main"], tables: ["assessments"],
    title: "Fill the gaps, then check again",
    text: "Company 2 gets a pending assessment for each circular of the last 30 days it hasn't got, then one circular.assess per pending one: steps 10 to 13, for company 2 only.",
    code: "refresh_company(), add_assessments(), pending() · worker/pipeline.py",
    moves: [["add missing", "s15>assessments", 0.03, 0.3, "data"], ["3 tasks", "s15>w2", 0.38, 0.62, "svc"], ["XADD ×3", "w2>main", 0.68, 0.94, "queue"]],
    marks: [
      [0.3, { rows: { assessments: [A1("done", "true", WHY1), ["2", "98", "pending", "(cleared)", ""], ["2", "97", "pending", "(cleared)", ""],
                                    ["2", "99", "done", "true", "answered after the change: kept"], ["2", "96", "pending", "", "added: read in the last 30 days"]] } }],
      [0.94, { slots: { main: ["98 · 2", "97 · 2", "96 · 2"] }, sub: { w2: W },
               log: ["redis", "XADD rci:tasks * type circular.assess company_id 2 circular_id 98  (and 97, 96)"] }],
    ],
  },

  // ── Keeping it all right (steps 16 to 18) ──
  {
    story: 4, ref: "step 16", dur: 8400, focus: ["watcher", "api", "pdf", "main"], tables: ["producers"],
    title: "Every change queues its task",
    text: "The worker never looks in Postgres for work: everything it does arrives as a task, queued right after its change is saved, so it always finds the change.",
    code: "enqueue() · common/queue.py",
    moves: [["circular.read", "watcher>pdf", 0.04, 0.3, "queue"], ["policy.check", "api>main", 0.2, 0.48, "queue"],
            ["Reprocess", "api>pdf", 0.4, 0.66, "queue"], ["next steps", "reader>main", 0.6, 0.9, "queue"]],
    marks: [[0.05, { slots: { main: [] }, rows: { producers: [
      ["the watcher finds a new circular", "watcher", "circular.read (PDF lane)"],
      ["a company adds or changes its description", "api", "company.refresh (main)"],
      ["a policy is added, or saved again", "api", "policy.check (main)"],
      ["Reprocess on a circular not read yet", "api", "circular.read (PDF)"],
      ["Reprocess on a read circular", "api", "circular.assess (main), this company"],
      ["a circular is read", "reader", "circular.assess (main), one per company"],
      ["a company refresh finds pending checks", "worker", "circular.assess (main), one per circular"],
      ["sign-up, a control, a gap update, a teammate", "nobody", "none: nothing to judge"],
    ] } }]],
  },
  {
    story: 4, ref: "step 16", dur: 7600, focus: ["watcher", "api", "reader"], tables: ["redisDown"],
    title: "If Redis can't take a task",
    text: "A change is only finished when its task is on its lane, so nobody just logs a lost task. Each producer undoes, refuses or retries instead. Saving again always works.",
    code: "enqueue_or_undo() · api/database.py · fetch_new() · watcher/main.py",
    moves: [["✗ delete the row", "watcher>pdf", 0.05, 0.36, "bad"], ["✗ 503, try again", "api>main", 0.3, 0.62, "bad"],
            ["✗ no XACK", "reader>pending", 0.56, 0.9, "bad"]],
    marks: [[0.05, { rows: { redisDown: [
      ["the watcher", "deletes the circular's row: the next round tries again"],
      ["the api: a new policy, or a description change", "undoes it, then 503: try again"],
      ["the api: a policy saved, Reprocess", "503: saved, try again (saving again queues it)"],
      ["a worker, queueing its next tasks", "no XACK: the task runs again, and queues them again"],
    ] } }]],
  },
  {
    story: 4, ref: "step 16", dur: 7000, focus: ["api", "pdf", "main"], tables: [],
    title: "If Redis loses its data",
    text: "Redis keeps the lanes on disk, so a restart loses nothing. If its data is deleted, run manage.py requeue once: it queues again everything Postgres shows unfinished.",
    code: "requeue() · api/manage.py",
    moves: [["requeue", "api>pdf", 0.1, 0.5, "queue"], ["requeue", "api>main", 0.2, 0.6, "queue"]],
    marks: [[0.6, { log: [["app", "cd backend/api && uv run python manage.py requeue"], ["app", "3 unfinished: 3 queued, 0 already queued"]] }]],
  },
  {
    story: 4, ref: "step 17", dur: 8400, focus: ["s5", "ocr", "s17", "pending"], tables: ["kinds", "pdfPending"],
    title: "A service is down: wait",
    text: "The step is rolled back; what was saved before stays. OCR still loading, or Gemini answering 429: no XACK, wait 60 s, run the same task again, as long as it takes.",
    code: "should_wait(), RETRY_SECONDS · worker/failures.py · run_task() · worker/main.py",
    moves: [["page 1", "s5>ocr", 0.03, 0.2, "gpu"], ["refused", "ocr>s5", 0.22, 0.36, "bad"], ["ConnectError", "reader>s17", 0.4, 0.6, "bad"],
            ["stays pending", "s17>pending", 0.64, 0.88, "queue"]],
    marks: [
      [0.01, { sub: { reader: "read 100", pending: "100 → e02f…-1", circulars: "100 · new" },
               rows: { kinds: [["Wait", "OCR still loading; Gemini 429 (quota)", "stays pending; again after 60 s, as long as it takes"],
                               ["Retry", "a timeout; a 5xx; not the asked-for JSON; the same answer saved first", "again at once, up to 3 tries"],
                               ["Give up", "Gemini 400; no text in the PDF; the PDF missing from S3", "give_up(): failed, a copy in rci:dead, XACK"]],
                       pdfPending: [["1790831170001-0", "circular.read, circular 100", READER, "0 s", "1"]] } }],
      [0.6, { log: ["warn", "WARNING OCR or Gemini unavailable ([Errno 111] Connection refused); retrying"] }],
      [0.88, { sub: { reader: "read 100 · in 60 s" } }],
    ],
  },
  {
    story: 4, ref: "step 17", dur: 8000, focus: ["s6", "chat", "s17", "pending"], tables: ["kinds", "pdfPending"],
    title: "A hiccup: try again, up to 3 times",
    text: "A timeout, a server error, an answer not in the asked-for form, or another task saving the same answer first: tried again at once, up to 3 tries.",
    code: "should_retry(), MAX_TRIES · worker/failures.py",
    moves: [["summarise", "s6>chat", 0.03, 0.2, "ext"], ["not JSON", "chat>s6", 0.23, 0.38, "bad"], ["BadReply", "reader>s17", 0.42, 0.62, "bad"],
            ["try 2 of 3", "s17>pending", 0.66, 0.9, "queue"]],
    marks: [[0.62, { rows: { pdfPending: [["1790831170001-0", "circular.read, circular 100", READER, "0 s", "2"]] },
                     sub: { reader: "read 100 · try 2" },
                     log: ["warn", "WARNING {'type': 'circular.read', 'circular_id': '100'} failed (BadReply: not the asked-for JSON); trying again"] }]],
  },
  {
    story: 4, ref: "step 17", dur: 9000, focus: ["s17", "circulars", "dead", "marks", "pending"], tables: ["dead", "pdfPending"],
    title: "Give up: failed, and a copy in rci:dead",
    text: "Anything else, or the 3rd try: the circular is marked failed with the error (for a check, that company's assessment), a copy goes to rci:dead, the mark is deleted, then XACK.",
    code: "give_up() · worker/main.py",
    moves: [["ValueError", "reader>s17", 0.03, 0.2, "bad"], ["failed + error", "s17>circulars", 0.24, 0.46, "bad"],
            ["copy", "s17>dead", 0.5, 0.68, "bad"], ["DEL mark", "s17>marks", 0.7, 0.82, "queue"], ["XACK", "s17>pending", 0.84, 0.97, "ok"]],
    marks: [
      [0.46, { sub: { circulars: "100 · failed" },
               log: [["error", "ERROR {'type': 'circular.read', 'circular_id': '100'} failed for good"],
                     ["sql", "UPDATE circulars SET status = 'failed', error = 'ValueError: OCR found no text in the PDF' WHERE id = 100"], ["sql", "COMMIT"]] }],
      [0.68, { sub: { dead: "circular.read 100" },
               rows: { dead: [["type", "circular.read"], ["circular_id", "100"], ["stream", "rci:tasks:pdf (the lane it came from)"],
                              ["task_id", "1790831170001-0"], ["error", "ValueError: OCR found no text in the PDF"]] },
               log: ["redis", "XADD rci:dead * type circular.read circular_id 100 stream rci:tasks:pdf task_id 1790831170001-0 error 'ValueError: OCR found no text in the PDF'"] }],
      [0.97, { rows: { pdfPending: [] }, sub: { reader: W, pending: NOBODY },
               log: [["redis", "DEL rci:queued:circular_id=100:type=circular.read"], ["redis", "XACK rci:tasks:pdf workers 1790831170001-0"]] }],
    ],
  },
  {
    story: 4, ref: "step 17", dur: 7400, focus: ["s17", "api"], tables: ["rerun"],
    title: "Run it again",
    text: "Nothing re-runs failed work by itself: the same error would most likely come back. The console shows Why it failed; fix the cause, then press Reprocess or save again.",
    code: "reprocess_circular() · api/routes/circulars.py",
    moves: [["Reprocess", "api>pdf", 0.3, 0.75, "queue"]],
    marks: [[0.05, { rows: { rerun: [
      ["reading a circular", "fix the cause, then Reprocess", "the pages already read, the text, the summary"],
      ["one company's check", "Reprocess, signed in as that company", "its gaps and \"out of date\" answers"],
      ["a policy check", "save the policy again", "its embeddings and every saved answer"],
      ["a company refresh", "save the description again", "the to-dos already saved"],
    ] } }]],
  },
  {
    story: 4, ref: "step 18", dur: 8000, focus: ["reader", "pending", "s18"], tables: ["pdfPending"],
    title: "A worker dies mid-task",
    text: "It never sent XACK, so its task stays on the pending list under its name, the idle time growing. Everything it saved is in Postgres; its mark stops anyone queueing a copy.",
    code: "next_task() · worker/main.py",
    moves: [],
    marks: [
      [0.01, { sub: { reader: "✗ killed on page 3", pending: "101 → e02f…-1", circulars: "101 · new", ocrpages: "7b2e… · 2 pages" },
               rows: { pdfPending: [["1790831180002-0", "circular.read, circular 101", READER, "0 s", "1"]] } }],
      [0.4, { rows: { pdfPending: [["1790831180002-0", "circular.read, circular 101", READER, "150 s", "1"]] } }],
      [0.8, { rows: { pdfPending: [["1790831180002-0", "circular.read, circular 101", READER, "300 s", "1"]] } }],
    ],
  },
  {
    story: 4, ref: "step 18", dur: 9000, focus: ["reader", "pending", "s18"], tables: ["died", "pdfPending"],
    title: "Back under its name, or taken over",
    text: "Restarted by Docker, it keeps its name and finds its task at once. Replaced by up --build, it has a new name: after 5 minutes XAUTOCLAIM hands the task to a reader again.",
    code: "next_task() · worker/main.py · ocr_text() · worker/pipeline.py",
    moves: [["XAUTOCLAIM", "reader>pending", 0.3, 0.52, "queue"], ["1790…02-0", "pending>reader", 0.56, 0.78, "queue"]],
    marks: [
      [0.02, { sub: { reader: "new container: c9f5…-1" },
               rows: { died: [["while reading the PDF", "reads only the pages not saved yet (the page in progress again)"],
                              ["after the text was saved", "starts at the summary"],
                              ["after the circular was read", "only adds the companies' to-dos again"],
                              ["between two policy questions", "asks only the ones not answered yet"],
                              ["after the check was done", "has nothing to do"]] } }],
      [0.78, { sub: { reader: "read 101, from page 3", pending: "101 → c9f5…-1" },
               rows: { pdfPending: [["1790831180002-0", "circular.read, circular 101", "c9f550b306ee-1", "0 s", "2"]] },
               log: [["redis", "XAUTOCLAIM rci:tasks:pdf workers c9f550b306ee-1 300000 0-0 COUNT 1 → 1790831180002-0"],
                     ["log", "INFO #101: 2 pages OCR'd before, carrying on"]] }],
    ],
  },
];

export default {
  id: "worker",
  tab: "Worker",
  hint: "as in INTERNALS.md",
  heading: "The worker, in detail",
  lead: "Everything the worker does, in the 18 steps of backend/worker/INTERNALS.md and with its example: circular 98, a 3-page PDF whose last page is blank; company 1, an NBFC with four RBI policies; company 2, a stock broker. Each numbered box in the picture is one of those steps. Under the picture, the rows each step changes, and every log line, Redis command and SQL statement.",
  label: "The worker: tasks arrive on two Redis lanes from the watcher and the api; the reader and two workers take them; the numbered boxes are INTERNALS.md's steps 4 to 18; on the right, the services they call and the Postgres tables they write.",
  refDoc: "INTERNALS.md",
  size: [1180, 664],
  groups: [[10, 30, 216, 112, "16 · who queues tasks"], [10, 152, 216, 496, "Redis"], [241, 152, 188, 328, "1–3 · the program, ×3"],
           [433, 30, 222, 506, "4–9 · the reader reads"], [657, 30, 222, 506, "10–15 · workers check"],
           [433, 552, 446, 100, "17–18 · keeping it right"], [880, 30, 288, 198, "services it calls"], [880, 240, 288, 314, "Postgres tables"]],
  nodes,
  edges,
  tables,
  quietEdges: true,
  start: { rows: { circulars: [CIRC_NEW],
                   settings: [["LANES", "pdf for the reader; main for each worker"], ["GEMINI_API_KEY", "required: without it, it stops"],
                              ["CLAIM_IDLE_SECONDS", "300: take over a task idle 5 minutes"], ["RETRY_SECONDS", "60: wait while a service is down"],
                              ["LOOKBACK_DAYS", "30: skip older circulars"], ["MATCH_TOP_K", "3: policies Gemini checks"]] } },
  stories: ["The worker itself · steps 1 to 3", "Reading a circular · steps 4 to 9 · the reader",
            "Checking it for each company · steps 10 to 13 · the workers", "The other tasks · steps 14 and 15",
            "Keeping it all right · steps 16 to 18"],
  steps,
};
